### ISSUE TITLE
ریز بودن سایز نوشته ها و ارقام

### ISSUE THREAD

**Issue by rastikerdar** [omid/Persian-Calendar-for-Gnome-Shell#10]
اگر امکان تنظیم سایز هم وجود داشت که خیلی خوب می‌شد.

![screenshot from 2016-04-07 23-22-48](https://cloud.githubusercontent.com/assets/3116038/14363079/af982b18-fd17-11e5-9e1c-e11668b2166b.png)

با تشکر

**Comment by xtoolkit** [comment]
سلام
به دلیل مشکل با اکثر پوسته ها، لطفا برای تاریخ عددی امکان تغییر رنگ و اندازه فونت رو قرار بدید
تشکر

**Comment by omid** [comment]
سلام،

من فعلن وقت ندارم که روی این تغییر کار کنم. اگر کسی می‌تونه کمک کنه ممنون می‌شم.

سپاس

**Comment by msm1365** [comment]
فکر میکنم مشکل مربوط به فونت باشد نه سایز کلمات

**Comment by omid** [comment]
در مورد فونت، فونت پیش فرض گنوم استفاده شده.

در مورد رنگ، تو نسخه آخر مجبور شدم خودم رنگ رو توی سی.اس.اس بذارم، باید بگردم کلاس سی.اس.اسی که برای خود گنوم هست رو بذارم که با تم‌های مختلف سازگار باشه.

**Comment by omid** [comment]
شاید بد نباشه @behdad هم تو بحث فونت فارسی گنوم باشه

**Comment by msm1365** [comment]
فونت پیش فرض گنوم برای انگلیسی خوبه
برای فارسی باید یک فونت دیگه استفاده بشه
مثلا فونت یکان یا شبنم البته نمیدونم چه شکلی میشه

**Comment by omid** [comment]
درست می‌گی...
اما من ترجیح می‌دم از پایه (یعنی گنوم) درست بشه تا اینکه من بخوام ماله بکشم روی مسایل!
برای همین هم @behdad رو تگ کردم تا بیاد و حداقل اگر پیشنهادی داره بگه.

**Comment by behdad** [comment]
سلام. نظر خاصی ندارم الان.  فونت‌های نوتو رو امتحان کنین شاید بد نباشه.
https://www.google.com/get/noto/

**Comment by omid** [comment]
خوب پس می‌شه از درست شدن فونت گنوم دست کشید :laughing: 

@msm1365 @xtoolkit @rastikerdar 
به نظرتون کدوم فونت فارسی بهتره برای این کار؟
از فونت‌های خود برادر راستی‌کردار یا صالح سوزنچی؟

**Comment by rastikerdar** [comment]
فکر نمی کنم نیازی به تغییر فونت باشه.

اگر کسی نیاز داشت میتونه بره این آدرس:
~/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/stylesheet.css
و اینو اضافه کنه:

```css
.pcalendar-day, .pcalendar-date-label, .pcalendar-event-label {
  font-size: 16px;
  font-family: shabnam, dejavu sans;
}
```

سپس
`alt+f2`
و 
`r`

**Comment by xtoolkit** [comment]
![screenshot from 2016-07-22 01-52-18](https://cloud.githubusercontent.com/assets/8210666/17039327/208d1b00-4faf-11e6-9d17-ed0a8a65887f.png)
والا اینه تو اکثر پوسته های
Arc
بیس!
همون امکان رنگ ها و اندازه هم باشه یکاریش میکنیم :D

**Comment by omid** [comment]
نسخه جدیدی منتشر کردم.
سعی کردم با تم‌های روشن هم سازگار بشه.

**Comment by morealaz** [comment]
<div dir="rtl">
فونت‌های آقای راستی‌کردار عزیز می‌تونه گزینه خیلی خوبی باشه. به عنوان نمونه فونت وزیر دارای نسخه‌ای به نام Vazir WOL می‌باشد که بدون نسخه لاتین هست و می‌تونه به عنوان گزینه مناسبی در کنار فونت لاتین دلخواه سیستم به عنوان فونت پیش فرض فارسی مورد استفاده قرار بگیره. البته با قدری تغییر در تنظیمات fontconfig
اینم نتیجه استفاده از این فونت:
</div>

![image](https://user-images.githubusercontent.com/2796369/31961424-365c77aa-b8ea-11e7-95bf-3eec2cb57e3a.png)

**Comment by omid** [comment]
@morealaz 
خوب قربون دست‌تون، یا پول ریکوئست هم بدین دیگه :-)

**Comment by omid** [comment]
البته راه حل بلندمدت امکان تغییر فونت خواهد بود.
اما همین مورد، مشکل خیلی‌ها رو مرتفع می‌کنه

**Comment by morealaz** [comment]
>  خوب قربون دست‌تون، یا پول ریکوئست هم بدین دیگه :-)

<div dir="rtl">
این تغییرات مربوط به سیستم میشه و ربطی به این افزونه نداره. در واقع فونت پیش‌فرض فارسی سیستم تغییر میکنه. برای اینکار فایل <code>local.conf</code> رو در مسیر <code dir="ltr">/etc/fonts/local.conf</code> با محتویات زیر بسازید:
</div >

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <!-- Default font for the fa_FA locale (no fc-match pattern) -->
  <match>
    <test compare="contains" name="lang">
      <string>fa</string>
    </test>
    <edit mode="prepend" name="family">
      <string>Vazir WOL</string>
    </edit>
  </match>
  <alias>
    <family>serif</family>
      <prefer>
       <family>Vazir WOL</family>
      	<family>Noto Serif</family>
      	<family>Heuristica</family>
	<family>Noto Color Emoji</family>
      </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
      <prefer>
	<family>Vazir WOL</family>
	<family>Noto Sans</family>
	<family>Droid Sans</family>
	<family>Noto Color Emoji</family>
      </prefer>
  </alias>
  <alias>
    <family>monospace</family>
      <prefer>
       <family>Vazir WOL</family>
	<family>Hack</family>
	<family>Noto Sans Mono</family>
	<family>Liberation Mono</family>
	<family>Droid Sans Mono</family>
	<family>DejaVu Sans Mono</family>
	<family>Noto Color Emoji</family>
      </prefer>
  </alias>
</fontconfig>
```
<div dir="rtl">
زیر قسمتهای
 serif و sans-serif و monospace
 میتونید فونت دلخواهتون رو به ترتیب اولویت با فرمتی که در اینجا به عنوان نمونه میبینید قرار بدهید ولی باید فونت Vazir WOL رو به عنوان اولین گزینه قرار بدهید و البته که یادتون نره فونت وزیر رو نصب کرده باشید در سیستم.
</div>

**Comment by omid** [comment]
یک نسخه با فونت وزیر منتشر کردم....
البته باید منتظر تایید بمونیم.

امیدوارم زیاد باگ نداشته باشه :)

**Comment by msm1365** [comment]
برای نسخه جدید دو تا تغییر دادم عکسشو میذارم اگه خوشتون اومد توی نسخه اصلی بذارینش.
 اول اینکه آندرلاین برای منوی بالا برداشتم
البته آندرلاین به روزهای مناسبتی هم سرایت کرد با این حال راضی بودم ازش 
دوم اینکه برای روزهای مناسبت دار و تعطیل رنگ سبز روشن انتخاب کردم
البته کاش بین روزهای تعطیل و روزهای فقط مناسبتی میشد تفکیک قائل شد. توی فایل سی اس اسش چیزی 
ندیدم
و البته من فونت انگور استفاده میکنم



![screenshot from 2017-11-03 07-17-44](https://user-images.githubusercontent.com/12663667/32360021-72afb97c-c067-11e7-9b23-cec6374ff9a3.png)

**Comment by omid** [comment]
من موافق نیستم.

استایل روزهای مناسبتی (آندرلاین) استایل پیشفرض تقویم گنومه، دلیل استفاده از اون استایل‌ها هم اینه که تا حد ممکن با تم‌های گنوم سازگار باشه.
تغییر رنگ هم به دلیل اینکه با تم‌های مختلف سازگار نیست رد می‌کنم.
روزهای مناسبتی و روزهای تغطیل توی «بولد» بودن متفاوتند.

ممنون

**Comment by rastikerdar** [comment]
اساسا بحث های رنگ آمیزی یا هنری به حوزه قالب و استایل مربوط میشه که در آن سلیقه‌ها بسیار منتوع است.
در واقع اپلیکیش باید از قاعده کلی محیط پیروی کنه و تا آنجا که می‌تونه نباید در این زمینه اعمال سلیقه کنه. مثلا حتی همین بحث فونت هم در حالت حرفه ای نباید بالاجبار در برنامه اعمال بشه و شاید بهتر می‌بود که به شکل یک چک‌باکس در قسمت کانفیگ برنامه به عنوان یک آپشن مطرح می‌شد. هر چند که من خودم شکل فعلی رو با فونت  و سایز جدید خیلی بیشتر می‌پسندم و دیگه با هر بار آپدیت نمی‌رم دستی فایل استایل رو تغییر بدم.

**Comment by omid** [comment]
@rastikerdar 
در مورد تغییر فونت، گذاشتن فونت وزیر موقته.
در حقیقت اولین قدم از تغییر اصلی که شامل افزودن فیلد تعیین فونت (+سایز) است.
برای همین این ایشو بسته نشده :دی

**Comment by behdad** [comment]
کسی لطف کنه یه وصله برای این فایل بفرسته خوب میشه:
https://cgit.freedesktop.org/fontconfig/tree/conf.d/65-fonts-persian.conf

**Comment by morealaz** [comment]
@behdad 
اگر بشه فونت های جدید فارسی مثل فونت های [آقای راستی کردار](https://rastikerdar.github.io/)  و فونت های [آقای موحدیان](https://bitbucket.org/dma8hm1334/) رو اضافه کنیم خیلی خوب میشه. بخصوص کلاس های 

- Persian_serif
- Persian_sans-serif
- Persian_monospace
- Persian_title
- Persian_fantasy
- Persian_square

خیلی میتونه در شخصی سازی تنظیمات فونت نرم افزار های فارسی و سیستم کمک کنه. من خودم تا حالا به این کلاس بندی ها دقت نکرده بودم 😄

**Comment by xtoolkit** [comment]
از اونجا که الان گنوم میزکار پیشفرض اوبونتو شده و به نظر من راه حل موقتی هم خیلی خوب هست تا به راه حل صحیح برسید.
شما فعلا قابلیت تنظیم دستی فونت دلخواه رو بزارید تا ببینیم چی میشه.
ممنون

**Comment by Bonsitar** [comment]
.سلام
با @msm1365 در مورد حذف اندرلاین زیر تقویم در پنل موافقم 
در تم هایی نظیر Arc 
گاهی خوندن تقویم در یک نگاه سخت میشه (نظر شخصی)
و تغییر فایل  ها بعد از هر اپدیت کار وقت گیریه
 خواستم بگم اگه امکانش هست یه چک باکس به تنظیمات اصافه کنید که این مورد به صورت انتخابی توسط کاربر در بیاد (که دوست داشته باشه در مناسبت ها زیر تقویم در پنل اندرلاین باشه یا نه!
متاسفانه جاوا اسکریپت و سی اس اس بلد نیستم که بتونم این کارو انجام بدم پس اگه یکی از دوستان لطف کنه و این امکان رو اضافه کنه عالی میشه.
موفق باشید.
@omid

**Comment by iman-salmani** [comment]
سلام و خسته نباشید

> استایل روزهای مناسبتی (آندرلاین) استایل پیشفرض تقویم گنومه، دلیل استفاده از اون استایل‌ها هم اینه که تا حد ممکن با تم‌های گنوم سازگار باشه.

من از فدورا ۳۰ (گنوم ۳.۳۲) استفاده می کنم 
![example](https://previews.dropbox.com/p/thumb/AAdNfGoAQmhYqg7a3k5uWH14jHPPaodm34bhXD7NZNDsLhgKD_b2cPpGDmZ0Y3HbSBcoTan15kqoQ1AMm1U5nyeG5UNYWzYNohUbqdw6l1Ck76CQTpZfLegtdU_X2LJzQvUDGkkPaOLA-wupMmGtUgYY3PfqZ2GeU3dbtJbg2PbUEhjvXqlBxo0E_azOeQZpDra81ZXgkevJswFfMyTYDI6g3-_EtLRYykSVMbVWniZmCJ3M_Esv-aaZHNOBMW6sMi4TGyejNCA6A0Oeuuffmmq39Z56gAvZGKvjnD9wQwy9FwDoXyT2F5HM7wZSnkGlZ4HBO0mpXwc91E2ajhgQXIO2/p.png)
تقویم گنوم مناسبت ها را با نقطه زیر آنها مشخص می کند.

**Comment by omid** [comment]
به نظرم تمامی مواردی که اینجا ذکر شده حل شده.

با یادی از آقای راستی‌کردار که دیگه بین‌مون نیستند 😢
