### ISSUE TITLE
مشکل باز نکردن تنظیمات 

### ISSUE THREAD

**Issue by mohammadsh07** [omid/Persian-Calendar-for-Gnome-Shell#106]
![Screenshot from 2022-04-18 11-35-57](https://user-images.githubusercontent.com/86713112/163770800-3747ea6b-7e69-4a64-ab17-2f21b98a2e69.png)

**Comment by omid** [comment]
سلام،
لطفن نسخه گنوم‌شل و نسخه افزونه رو بگید.
و اینکه چطوری افزونه رو نصب کردید؟

**Comment by mohammadsh07** [comment]
سلام خسته نباشید
GNOME Shell 3.36.9
طبق داکیومنت رفتم جلو
Clone the repository
Go to the cloned directory
run make command in the terminal
Restart Gnome-shell. (ALT+F2, r, Enter)
You may need to enable the extension via Gnome Extensions Application
و اینکه فایل رو clone  کردم که میشه آخرین نسخه .

**Comment by omid** [comment]
خوب چرا Recommended way رو نرفتید؟
لطفن افزونه رو حذف کنید و از راه «پیشنهاد شده» نصب کنید.

**Comment by mohammadsh07** [comment]
> خوب چرا Recommended way رو نرفتید؟ لطفن افزونه رو حذف کنید و از راه «پیشنهاد شده» نصب کنید.
خیلی تست کردم نشد ...

**Comment by omid** [comment]
پس بگید چرا نتونستید از روش توصیع شده نصب کنید؟
آیا بخش Troubleshooting رو خوندید؟

**Comment by mohammadsh07** [comment]
از روش هایی که گفتین رفتم تست کردم نشد که نشد....   (:

**Comment by omid** [comment]
دقیقن توضیح بدید چکار کردید و چه خطاهایی دیدید که بشه مشکل رو برطرف کرد.

**Comment by omid** [comment]
ممنون. اگر مشکل حل نشد، تیکت رو مجدد باز کنید.

**Comment by mohammadsh07** [comment]
با ارتقا به ubuntu 22.04 مشکل رفع شد!
