### ISSUE TITLE
تنظیم موقعیت پنل

### ISSUE THREAD

**Issue by iman-salmani** [omid/Persian-Calendar-for-Gnome-Shell#109]
سلام وقت بخیر
موقیت پنل همیشه مایل به راست هست. واضح تر بگم اون زائده پنل سمت چپ پنل هست و خوده پنل به نصبت لیبل تراز نیست و اومده سمت چپ.
که بنظرم مخصوصا توی وسط چین نمای خوبی نداره.

**چیزی که الان هست:**
![Screenshot from 2022-06-06 17-52-10](https://user-images.githubusercontent.com/32843050/172168907-d66045f8-64d6-4c5b-b439-fa8cdbe46b62.png)

**وسط چین:**
![Screenshot from 2022-06-06 17-53-45](https://user-images.githubusercontent.com/32843050/172169153-cfed8e25-95cd-40e1-8037-05bfa5cc14a8.png)
کد تصویر بالا:
`this.menu._arrowAlignment = 0.5;`

به ۳ حالت می شه اینو درست کرد:
- همیشه وسط چین
- استایل مخصوص برای هر حالت (یعنی موقعی که پنل سمت راست هست راست چین و ...)
- اضافه کردن امکان تنظیم تراز پنل برای کاربر 

برای من همون وسط چین کفایت می کنه.
نظرتون شما چیه؟

**Comment by omid** [comment]
سلام،
ممنون، خیلی هم عالی.
به نظر من هم همون وسط‌چین اوکیه.
توی پول‌ریکوئست فعالی که هست درستش کردم.
به زودی مرج و منتشر می‌شه.
