### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by mhkarimi1383** [omid/Persian-Calendar-for-Gnome-Shell#117]
In ArchLinux I got Gnome 43.alpha using `fcgu` repository
I will test out if it works w/o any extra workout and put the result here ;)

**Comment by mhkarimi1383** [comment]
Hello again
I just bumped up the version inside metadata but I'm getting error below
![image](https://user-images.githubusercontent.com/28821440/180512047-0041d127-d410-4e46-8074-682e36372ea9.png)

**Comment by mhkarimi1383** [comment]
Here is the result

I'm also having a problem where my Persian Language is not working

![image](https://user-images.githubusercontent.com/28821440/180513268-b0462d62-52a1-4afe-8f5c-2d41292764ec.png)

**Comment by omid** [comment]
So... now it's on you to fix the issues and create a PR. :)

**Comment by mhkarimi1383** [comment]
> So... now it's on you to fix the issues and create a PR. :)

Persian Language was not working in older gnome versions also

**Comment by omid** [comment]
AFAIK it does :)
I use it right now

**Comment by mhkarimi1383** [comment]
It was not working for me :(

**Comment by mhkarimi1383** [comment]
I have enabled `fa_IR UTF-8` in my `locale.gen`

**Comment by omid** [comment]
> I have enabled `fa_IR UTF-8` in my `locale.gen`

and?

If you have the latest version of the extension, the persian lang should work without installing persian locale.

**Comment by mhkarimi1383** [comment]
> > I have enabled `fa_IR UTF-8` in my `locale.gen`
> 
> and?
> 
> If you have the latest version of the extension, the persian lang should work without installing persian locale.

For me it's not working how can I check version?

**Comment by omid** [comment]
Version of the extension is in the `metadata.json` file.

**Comment by mhkarimi1383** [comment]
Oh I see
I'm running version 98

**Comment by omid** [comment]
AFAICR it should work without the need of installing Persian locale

**Comment by mhkarimi1383** [comment]
> AFAICR it should work without the need of installing Persian locale

How can I chack if something is wrong with me?
maybe a required package or file

**Comment by omid** [comment]
How did you install the extension? Github or extensions.gnome.org?

**Comment by mhkarimi1383** [comment]
> How did you install the extension? Github or extensions.gnome.org?

extensions.gnome.org

**Comment by omid** [comment]
Can you go to the state that you said the Persian language doesn't work?

**Comment by mhkarimi1383** [comment]
Currently it's not working

**Comment by omid** [comment]
So please compress all contents of the following folder and send them here:

`~/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com`

**Comment by mhkarimi1383** [comment]
I will do it ASAP

**Comment by omid** [comment]
Also please keep the following command running, and then press "Alt+F2" then type "r" and then "enter".

```
sudo journalctl -f -g PersianCalendar@oxygenws.com
```

then paste the output here (if there is any)

**Comment by mhkarimi1383** [comment]
[PersianCalendar@oxygenws.com.tar.gz](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/files/9205413/PersianCalendar%40oxygenws.com.tar.gz)

**Comment by mhkarimi1383** [comment]
There is no out put with the command that you sent

**Comment by omid** [comment]
There should be a file in the `locale` folder in `~/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com`, but there isn't any!

I checked the extension in `extensions.gnome.org` and it exists. So most probably you deleted it manually.
So you can remove the whole extension and add it again.

**Comment by mhkarimi1383** [comment]
> There should be a file in the `locale` folder in `~/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com`, but there isn't any!
> 
> I checked the extension in `extensions.gnome.org` and it exists. So most probably you deleted it manually. So you can remove the whole extension and add it again.

I have not removed any file but I will reinstall it

**Comment by mhkarimi1383** [comment]
Reinstalled extension but having same problem

also I have noticed typo problems in file names for locale :) 
e.g `persian-calendar.po` should be `persian-calender.po`

**Comment by omid** [comment]
I downloaded the file directly from ego (extensions.gnome.org) and the locale is there.
So if you are sure sure your setup in OK, then it can be a bug in gnome-shell (alpha)

And `calender` is wrong, `calendar` is correct. If you are referring to this.

**Comment by mhkarimi1383** [comment]
My files also complete....

**Comment by omid** [comment]
Last time it was not complete. So again compress and send the directory.

**Comment by mhkarimi1383** [comment]
files are not complete again  I think something is happening after installation or restarting my shell

**Comment by SomeGuy04** [comment]
ik im late but do you have packages ``ttf-liberation``` and ```ttf-dejavu``` installed on your arch setup?

**Comment by mhkarimi1383** [comment]
I will check but it should not be related to my problem that files are removing automatically :(

**Comment by mhkarimi1383** [comment]
`ttf-dejavu` was missing I will reinstall plugin and tell the result here

**Comment by mhkarimi1383** [comment]
Not worked :/

**Comment by mhkarimi1383** [comment]
and `locale` dir is empty again :(

**Comment by omid** [comment]
Since the release of 43 is close, I checked it and seems like you don't have `po2json` locally and so there is no way to generate the language files. You can install is with `npm -g install po2json` command.
