### ISSUE TITLE
پیروی از قلم پیش‌فرض (fontconfig)

### ISSUE THREAD

**Issue by UsernamesAreFuckedUp** [omid/Persian-Calendar-for-Gnome-Shell#121]
سلام. همون‌طور که مستحظر هستید، یکپارچه نبودن قلم در سیستم‌عامل روی اعصابه. اگر که این افزونه از قلم‌[های] پیش‌فرض استفاده کنه این مشکل هم بر طرف می‌شه. متشکرم.

**Comment by omid** [comment]
سلام، به نظرم مشکل با پیاده‌سازی این فیچر برطرف می‌شه:
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/10
