### ISSUE TITLE
تقویم شمسی برای مدیر پرونده

### ISSUE THREAD

**Issue by goodosuser** [omid/Persian-Calendar-for-Gnome-Shell#126]
سلام
خیلی افزونه خوبی هست خیلی عالی می شه که مدیر پرونده گنوم رو هم بشه شمسی داشت.

**Comment by omid** [comment]
سلام،
ممنونم. نه متاسفانه ممکن نیست.
تا جایی که یادمه، اون بخش توسط کتابخانه‌های سی انجام میشه و باید کل اون کتابخونه این قابلیت رو اضافه کنه و ... خلاصه اینکه قله ای است که هنوز فتح نشده.

**Comment by goodosuser** [comment]
سلام ممنونقبلاً کی دی ای فتحش کرده بود اما اخیرا اون هم میلادی شده!در تاریخ ۲۱ اکتبر ۲۰۲۲ ۳:۲۲، Omid Rad ***@***.***> نوشت:

سلام،

ممنونم. نه متاسفانه ممکن نیست.

تا جایی که یادمه، اون بخش توسط کتابخانه‌های سی انجام میشه و باید کل اون کتابخونه این قابلیت رو اضافه کنه و ... خلاصه اینکه قله ای است که هنوز فتح نشده.

**Comment by omid** [comment]
نه، منظورم گنوم بود
کتابخونه‌های این دو متفاوتند

**Comment by SCR-IR** [comment]
این موضوع باید از طریق سفارشی‌سازی تنظیمات «منطقه و زبان» در گنوم انجام بشه که متأسفانه گنوم هنوز پیشرفت مطلوبی نداشته و مثل ویندوز نیست که از گاهشماری‌های گوناگون پشتیبانی کنه. ای کاش دوستان گنوم‌کار زودتر اقدامی کنند. اگر می‌شناسید یا ارتباط دارید، به ایشان منتقل بفرمایید

**Comment by goodosuser** [comment]
سلامبعید می دونم.کی دی ای هم که داشت الان نداره.می شه با افزونه های مدیر پرونده ها فعلا حل کرد موضوع روبازم به ویندوزدر تاریخ ۱۲ دسامبر ۲۰۲۲ ۱۱:۲۰، SCR-IR ***@***.***> نوشت:
این موضوع باید از طریق سفارشی‌سازی تنظیمات «منطقه و زبان» در گنوم انجام بشه که متأسفانه گنوم هنوز پیشرفت مطلوبی نداشته و مثل ویندوز نیست که از گاهشماری‌های گوناگون پشتیبانی کنه. ای کاش دوستان گنوم‌کار زودتر اقدامی کنند. اگر می‌شناسید یا ارتباط دارید، به ایشان منتقل بفرمایید
