### ISSUE TITLE
نمایش روز هفته

### ISSUE THREAD

**Issue by mkalantar** [omid/Persian-Calendar-for-Gnome-Shell#13]
سلام
به فرمت‌ها اگه روز هفته هم اضافه بشه جالب‌تر میشه، مثلا بنویسه سه‌شنبه ۱۸ مهر

**Comment by omid** [comment]
سلام،

ایده‌ی خوبیه.... به نظرم شما که سابقه‌ی برنامه‌نویسی دارید هم می‌تونید خودتون درستش کنید و پول ریکوئست بدید :-)
چرا که نه؟ 👍 

ممنون.

**Comment by msm1365** [comment]
روز هفته به منوی بالا اضافه بشه خیلی بهتره. مثل تقویم خود گنوم

**Comment by omid** [comment]
### انجام شد :-)

**Comment by rastikerdar** [comment]
خیلی جالبه همین الان داشتم به همین موضوع فکر می‌کردم که دیدم ایمیل برام اومده اوکی شده. دستمریزاد! کیف کردم

**Comment by mkalantar** [comment]
دم شما گرم.
عالی
