### ISSUE TITLE
امکان جایگزین شدن تقویم پیشفرض گنوم

### ISSUE THREAD

**Issue by medicamin** [omid/Persian-Calendar-for-Gnome-Shell#130]
سلام. آیا از نظر فنی این امکان وجود دارد که این تقویم شمسی جایگزین تقویم میلادی ای شود که با کلیک روی ساعت گنوم نمایش داده می شود؟
همچنین اگر بشود تقویم را وارد منوی سیستم هم کرد. مثلا یک دکمه در منوی سیستم همون جایی که دکمه های سیستم وجود دارن مثلا wifi و ...) که متن آن تاریخ امروز باشد و با کلیک روی آن تقویم شمسی در زیرش باز شود.

**Comment by omid** [comment]
سلام، آره، فکر کنم همه مواردی که گفتید از نظر فنی ممکن باشه.
اما هدف این افزونه تغییر سیستم اصلی گنوم نبوده.
یه سری اکستنشن هست که تقویم اصلی گنوم رو مخفی کنند. می‌تونید از این طریق اون رو مخفی کنید. اما تاریخچه notificationها رو از دست می‌دید. (شاید برای این هم اکستنشنی باشه!)

در موردِ مورد دوم هم به نظر من ux خوبی نداشته باشه. اما به هر حال، اگر کسی این رو آپشنال بنویسه و PR بده، اکسپت می‌کنم!

**Comment by medicamin** [comment]
ممنون بابت پاسخ فوق سریع!
بیشتر هدفم از مخفی کردن تقویم گنوم اینه که "یک" تقویم در سیستم نمایش داده بشه. اینجوری سادگی بیشتری هم دیده میشه و انگار که چیزی اضافه نشده. بهرحال رئیس شمایی و ممنون که جواب دادی
