### ISSUE TITLE
پیشنهاد تغییر واژگانی

### ISSUE THREAD

**Issue by SCR-IR** [omid/Persian-Calendar-for-Gnome-Shell#132]
سلام
بهتر نیست در اسامی متغیرها، توابع و غیره، به‌جای «**hijri**» از «**islamic**» استفاده شود؟

چراکه اصطلاح «هجری» به‌معنای شروع شمارش از سال هجرت پیامبر (ص) می‌باشد و گاهشماری‌های **شمسی** و **قمری**، هردو از نوع «هجری» هستند.
لذا صحیح‌تر است که برای تفکیک این‌دو از واژگان شمسی - قمری یا واژگان persian - islamic در کد منبع استفاده شود.

**Comment by SCR-IR** [comment]
تقویم قمری، به آن معنی که بر اساس هلال ماه باشد، **بله** قبل از بعثت حضرت محمّد (ص) هم رایج بوده است.
مثلاً تا قبل از هجرت، مبدأ شمارش بر اساس سال حمله‌ی ابرهه (داستان اصحاب فیل) محاسبه می‌شد و قبل‌تر از آن هم نسبت به وقایع قدیمی‌تر مربوط به پیامبران پیشین. در طول زمان هم روش‌های مختلفی وجود داشته که متفاوت بوده از جمله ماه سیزدهم که بعداً منسوخ شده.

گاهشماری‌های دیگری نیز بر اساس هلال ماه وجود داشته، از جمله برخی روش‌های عبری مختص یهودیان و حتی بعضی روش‌ها در آسیای شرقی.

اما چیزی که الآن در جهان بسیار مشهور هست، همین گاهشماری **هجری‌قمری** رایج بین مسلمانان دنیاست که به ۲ روش: **قراردادی** و **رؤیت هلال** تنظیم می‌شود. چیزی که ما استفاده می‌کنیم، بر اساس رؤیت هلال ماه هست که حدود ۸۰ الی ۸۵ درصد قابل‌پیش‌بینی خواهد بود. اما اصل را بر رؤیت قرار می‌دهیم و اگر به احتمال ۱۵ الی ۲۰ درصد، تطابق نداشت، تقویم را به‌صورت دستی اصلاح می‌کنیم.

بحث درمورد انتخاب روش، در تخصص ما نیست و به مسائل فقهی مربوط می‌شود. لذا ما فعلاً بنابر رؤیت هلال ماه، احتیاط می‌کنیم تا اِن‌شاءاللّه بزودی توسط حضرت ولی‌عصر، تعیین تکلیف بشود.

**Comment by SCR-IR** [comment]
اما موضوعی که در ابتدا مطرح شد، مربوط به ابهام عبارت **hijri** هست. چراکه تقویم‌های **خورشیدی** و **قمری**، هردو از نوع **hijri** هستند. پس صحیح نیست که از این عبارت در کدنویسی استفاده کنیم و بهتر هست با islamic جایگزین بشود.

**Comment by SaeidArya** [comment]
داداشای گلم؛ این یه نام متغییر تو کد هست، هر عقل سلیمی که به این کد رجوع کنه می‌دونه داره از persianCalendar استفاده می‌کنه و دلیل و برهان استفاده‌ش رو هم هزار بار تو مدرسه توجیه شده.
لطفاً درست بردارید از مسایل بی مورد، وقت گرانبهاتون رو صرف هزاران کار مهم و ارزشمند دیگه بکنید.
