### ISSUE TITLE
امکان استفاده در اوبونتو و مینت

### ISSUE THREAD

**Issue by vbeh** [omid/Persian-Calendar-for-Gnome-Shell#133]
سلام بر شما
اول اینکه بسیار متشکرم که همچین تقویم کاربردی و زیبایی رو طراحی کردین واقعا خسته نباشید

خواستم بدونم الان یا در آینده امکان استفاده از این تقویم در Ubuntu و Mint هم وجود داره؟

**Comment by omid** [comment]
سلام،
همین الان هم باید امکانش باشه

**Comment by vbeh** [comment]
می‌شه روش نصب در مینت رو هم به توضیحات نصب اضافه کنید؟ چون دسکتاپ مینت سنامون هست و خیلی وقته توسعه‌ش از دسکتاپ گنوم فاصله گرفته ظاهرا افزونه‌های گنوم روی سینامون اجرا نمی‌شه. متاسفانه من دانشی در این زمینه ندارم اگر امکانش هست توضیح بدید. پیشاپیش بسیار ممنونم

**Comment by omid** [comment]
نحوه نصب فرقی نداره.
در حقیقت نسخه لینوکس اهمیتی نداره.
فقط باید از دسک‌تاپ گنوم ۳ (یا اصطلاحن gnome-shell) استفاده کنید.
یعنی دسکتاپ دیفالت مینت، سینامون، پشتیبانی نمی‌شه، مگر اینکه گنوم بریزید: https://itsfoss.com/install-gnome-linux-mint/
اما اوبونتو پیش‌فرض گنوم ۳ است و مشکلی نداره

**Comment by vbeh** [comment]
خیلی ممنون

**Comment by vbeh** [comment]
برنامه‌ای دارید که نسخه Flatpack ازش تهیه کنید؟

**Comment by omid** [comment]
کاربرد flatpak بیشتر برای برنامه‌های اجرایی است به نظرم.
در مورد اکستنشن، زیاد توجیحی نداره.
می‌تونید از این استفاده کنید مثلن:
https://flathub.org/apps/com.mattjakeman.ExtensionManager
