### ISSUE TITLE
مشکل ساخت خودکار دایرکتوری فونت

### ISSUE THREAD

**Issue by fakhamatia** [omid/Persian-Calendar-for-Gnome-Shell#138]
توی اوبونتو ۲۳.۱۰ وقتی افزونه رو نصب میکنم توی Home یک دایرکتوری font درست میکنه
![image](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/assets/20030910/d4fa66ab-d539-49c1-a840-e40fba472970)

**Comment by omid** [comment]
درسته، کد مشکل داره.
یادم نیست از کِی اینطوری شده!

**Comment by omid** [comment]
اینجا حل شد:
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/commit/0d0f61b6d386e930e01e04754e8b74ed3e6b7f02

اگر از آخرین نسخه گنوم (۴۵) استفاده می‌کنی، برات درست می‌شه.
در غیر این صورت باید تا اون موقع صبر کنی.
