### ISSUE TITLE
عدم نمایش تنظیمات در نوم ۴۵

### ISSUE THREAD

**Issue by ali-safapour** [omid/Persian-Calendar-for-Gnome-Shell#139]
این پیامی هست که موقع باز کردن تنظیمات افزونه در نوم ۴۵ نشون داده میشه:
![image](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/assets/91371249/f42c4bdc-39fe-49e1-b039-f56a4faf0d17)

**Comment by omid** [comment]
چه نسخه ای از افزونه رو نصب دارید؟
چطوری نصب کردید؟ از سایت گنوم اکستنشن؟

**Comment by ali-safapour** [comment]
نسخه ۱۰۷ رو نصب کردم از سایت نوم اکستنشنز. با سرچی که انجام دادم، متوجه شدم که gir1.2-gtkclutter-1.0 به صورت پیشفرض روی اوبونتو ۲۳٫۱۰ که از نوم ۴۵ استفاده میکنه وجود نداره و بخاطر همین، این ارور نمایش داده میشه. با نصب این پکیج مشکل حل شد.

یه مشکل دیگه هم که پیدا کردم، راجع به تنظیمات "ظاهر > موقعیت" هست. موقعیت فقط وقتی عوض میشه که من یه بار افزونه رو غیرفعال کنم و دوباره فعالش کنم. قبلا اینطوری نبود.

**Comment by omid** [comment]
ممنون. پس مشکل از اوبونتوئه در حقیقت.
اون مورد دوم هم به نظر مشکل (یا رفتار پیش‌فرض و جدید) گنوم باشه.

(تیکت رو می‌بندم، اگر فکر می‌کنی افزونه مشکلی داره، مجدد بازش کن لطفن.)

**Comment by omid** [comment]
سلام،
پیامی که توی Technical Details می‌بینید چیه دقیقن؟

**Comment by alirezaimi** [comment]
این پست مشکل رو حل کرد برای من 
https://github.com/yozoon/gnome-shell-extension-blyr/issues/26#issuecomment-726425004
با ارور زیر :

‍‍‍```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Clutter/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
