### ISSUE TITLE
The extension is incompatible with the current GNOME version

### ISSUE THREAD

**Issue by mahdi-marjani-moghadam** [omid/Persian-Calendar-for-Gnome-Shell#142]
با ورژن جدید کار نمیکنه

**Comment by omid** [comment]
چه ورژنی از گنوم و چه ورژنی از اکستنشن؟

**Comment by mahdi-marjani-moghadam** [comment]
GNOME Shell 45.1

بعدش پاک کردم دوباره نصب کردم درست شد. بعد از اپگرید این مشکل پیش اومده بود. 
ممنون از پیگیریت
