### ISSUE TITLE
انگلیسی بودن بعضی ارقام

### ISSUE THREAD

**Issue by RZHSSNZDH** [omid/Persian-Calendar-for-Gnome-Shell#144]
سلام
خسته نباشید؛
بعضی ارقام توی تقویم انگلیسی نمایش داده میشن مثل ارقام تاریخ‌های میلادی و قمری.

**Comment by omid** [comment]
سلام،
ممنون. اول نمی‌خواستم خودم حلش کنم... اما در حال انجام یه سری تغییرات بودم و این رو هم حل کردم 👍🏼 
به زودی منتشر می‌شه.
