### ISSUE TITLE
Error accessing settings

### ISSUE THREAD

**Issue by masoudamri** [omid/Persian-Calendar-for-Gnome-Shell#145]
Settings cannot be viewed from extension manager

The settings of extension PersianCalendar@oxygenws.com had an error:
```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Clutter/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```
![image](https://github.com/user-attachments/assets/d23c5c5c-85fb-42b3-9e9a-33f1931bca49)

**Comment by masoudamri** [comment]
masoud@masoud-Laptop-13-AMD-Ryzen-7040:~$ gnome-shell --version
GNOME Shell 46.0
masoud@masoud-Laptop-13-AMD-Ryzen-7040:~$ uname -a
Linux masoud-Laptop-13-AMD-Ryzen-7040 6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by omid** [comment]
Please follow the steps in this ticket:
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/139

And a PR to add the steps to the troubleshooting section of the readme file is very much appreciated 🙏🏻

**Comment by masoudamri** [comment]
You got it, chief. 
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/pull/146
Just do me a favor and squash the commits on merge!
Thanks

**Comment by omid** [comment]
Thanks a lot
Merged 🙏🏻
