### ISSUE TITLE
عدم نمایش کامل تنظیمات بعد از ورود مجدد به میزکار

### ISSUE THREAD

**Issue by Mamad026** [omid/Persian-Calendar-for-Gnome-Shell#16]
سلام. خسته نباشید میگم بابت افزونه عالی که  در حال توسعه ان هستید.
مشکل از ان جا ناشی میشود که پس از ورود دوباره از جی دی ام به میزکار کانفیگ اعمال شده به درستی در نوار نمایش داده نمی شود.
برای مثال زمانی که دستگاه ساسپند شده و دوباره از طریق جی دی ام به میزکار وارد میشوم به جای نمایش "۲۳ ابان"  اینطور نمایش داده میشود؛ "۲۳..."

**Comment by omid** [comment]
سلام،
ممنون.
این مشکل به گنوم یا یکی از افزونه‌های برمی‌گرده احتمالن، من هم یه مدتی این رو می‌دیدم، اما الان درست شده.
گنوم این قابلیت رو داره که زمانی که عرض گزینه‌هایی که اون بالا هست زیاد می‌شه، یه سری رو تبدیل به «...» می‌کنه

خلاصه اینکه، اگر از افزونه‌ی نمایش آب و هوا استفاده می‌کنی، اون رو غیرفعال کن ببین درست می‌شه یا نه. چون یادمه که اون برای من مشکل ایجاد می‌کرد.

**Comment by Mamad026** [comment]
بله یکی از افزونه های در حال اجرا بر روی نوار بالایی مربوط به افزونه 
open weather
می باشد, و در فرصت مناسب راهکار ارائه شده را امتحان کرده و نتیجه را خدمت شما عرض منمایم. 
همچنین تشکر از سرعت پاسخ گویی شما به مورد  فوق. 
موفق و پیروز باشید.

**Comment by rastikerdar** [comment]
با افزونه زیر فاصله بین افزونه‌ها رو کم کنید:
[extensions.gnome.org/extension/355/status-area-horizontal-spacing](https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/)
همچنین توی تنظیمات هواشناسی در قسمات تنظیمات
Layout
موارد اضافی رو بردارید تا افزونه خلاصه و عرضش کوتاه بشه. حتی می‌تونید اون رو به سمت چپ ساعت/پنل منتقل کنید.
![screenshot from 2018-01-14 06-05-22](https://user-images.githubusercontent.com/3116038/34912225-ed9e0884-f8f0-11e7-8c6a-9e1660a68b81.png)
