### ISSUE TITLE
وسط گذاشتن آیکون

### ISSUE THREAD

**Issue by SamadiPour** [omid/Persian-Calendar-for-Gnome-Shell#18]
قطعا بهترین افزونه ای هست که دارم
تنها مشکلی که من بهش برخوردم وسط نبودن آیکون هستش
من خودم با تغییر کد تونستم عوض کنم ولی قطعا اگر به صورت گزینه به تنظیمات اضافه بشه خیلی بهتر هستش

![screenshot from 2018-10-11 17-40-15](https://user-images.githubusercontent.com/24422125/46810303-43637e00-cd7d-11e8-97f7-982c193d3ae8.png)

همونطور که مشاهده میکنید افزونه در وسط نمای بهتری داره
تنظیم دستی این مورد با تغییر کدی که در عکس معلوم هست بسیار ساده هست
روش کار به صورت زیر است

> `sudo nautilus ~/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/`
open extension.js
change
`Main.panel.addToStatusArea('persian_calendar', _indicator);`
to
`Main.panel.addToStatusArea('persian_calendar', _indicator, 0, 'center');`
save and then press Alt+F2 write r press Enter

ولی اگر ممکنه لطفا خودتون به تنظیمات اضافه کنید
سپاس

**Comment by omid** [comment]
بسیار عالی.
یک گزینه جدید تو تنظیمات بیاد که موقعیت رو بشه از توی تنظیمات تنظیم کرد عالی می‌شه

**Comment by SamadiPour** [comment]
> بسیار عالی.
> یک گزینه جدید تو تنظیمات بیاد که موقعیت رو بشه از توی تنظیمات تنظیم کرد عالی می‌شه

به نظر زیاد کار سختی نیستش
من اون خط کد رو هم از افزونه دیگه ای پیدا کردم

خط 56
[https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/src/extension.js](url)

داخل تنظیمات برنامه هم قابل انتخاب هست که وسط|راست|چپ باشه یا با منو ی سیستم ادغام بشه

**Comment by omid** [comment]
@rastikerdar 
موقعیت آیکون رو می‌شه تعیین کرد. چه راست، چه وسط و چه چپ. صرفن باید یک عدد پاس بدیم به اون تابع

**Comment by omid** [comment]
یعنی یه کلمه گفتی بهترین افزونه :))
خلاصه اینکه جو گرفت و توسعه دادمش:

https://github.com/omid/Persian-Calendar-for-Gnome-Shell/commit/a2df78eec580517893db2ff33f703965703613df

**Comment by morealaz** [comment]
آقا در بهترین بودن شکی نیست. ایشالا قدم بعدی ادغام با تقویم گنوم باشه

**Comment by omid** [comment]
من بخوام همچین قدمی بردارم جر می‌خورم :))

**Comment by SamadiPour** [comment]
@omid 
ولی قطعا ارزشش رو داره
میگم اگه منبعی آموزشی چیزی هست بگو من یاد میگیرم میام کمک

**Comment by omid** [comment]
@SamadiPour 

متاسفانه تا جایی که من می‌دونم، منبع منسجم و تر و تمیزی وجود نداره
خیلی اوقات برای شروع از افزونه‌های مشابه استفاده می‌کنم
اما بعدن با از گوگل و رفرنس‌های جی.تی.کی۳ استفاده می‌کنم برای تر و تمیز کردن و استفاده از توابع مناسب و ...
گاهی اوقات هم مجبورم سورس کد پروژه گنوم‌شل توی گیت‌هاب/گیت‌لب رو بخونم... اون هم به جاوااسکریپته.

خلاصه اینکه روش توسعه‌ی عذاب‌آوری داره، اما نشدنی نیست :smiley:

**Comment by morealaz** [comment]
<div dir="rtl">
افزونه <a href="https://github.com/Daniel-Khodabakhsh/datetime-format">datetime-format</a>  یه کارایی روی نمایش تاریخ سیستم در تقویم گنوم انجام میده فکر کنم بد نیست یه نگاهی بهش بیاندازید
</div>
