### ISSUE TITLE
مشکل در نمایش تاریخ

### ISSUE THREAD

**Issue by meysampg** [omid/Persian-Calendar-for-Gnome-Shell#19]
سلام. خیلی وقت‌ها -مثل تصویر زیر- تاریخ تبدیل به … میشه و برای اصلاحش تنها راهی که تونستم پیدا کنم، غیرفعال و فعال کردن دوباره‌ی اکستنشنه.

![untitled](https://user-images.githubusercontent.com/1416085/47090141-2290a200-d22f-11e8-9743-98d83ca06dfd.png)

تنظیمات اکستنشن هم هموناییه که بصورت دیفالت بوده:
![screenshot from 2018-10-17 17-06-43](https://user-images.githubusercontent.com/1416085/47090159-2f14fa80-d22f-11e8-9013-2762f65d4fc2.png)

راه‌حلی برای حل این مشکل وجود داره؟

نسخه‌ی گنوم‌شل: ۳.۲۸.۳

**Comment by omid** [comment]
سلام،

این یک قابلیت نسبتن جدیده که فکر کنم توی گنوم ۳.۲۸ یا ۳.۲۶ اومد. البته مشکلاتی هم داره!
هیچ راهی تقریبن وجود نداره واسه درست کردنش، چون طول ابزارهایی که توی سمت راست نوار دارید زیاده.

یا اینکه چند تا افزونه رو که توی نوار بالا، سمت راست، هستند رو غیرفعال کنید
یا اینکه این رو نصب کنید:
https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/
یا اینکه یه مانیتور یا لپ‌تاپ بزرگ‌تر بخرید :smile_cat:

**Comment by rastikerdar** [comment]
من توی قسمت ویژگی‌های ویجت، فرمت رو این شکلی گذاشتم:
%ww %d
 مختصر و مفید میشه :)
![screenshot from 2018-10-17 19-29-40](https://user-images.githubusercontent.com/3116038/47100151-b53b3c00-d243-11e8-84a6-743495452353.png)

**Comment by meysampg** [comment]
@omid اکستنشنی که معرفی کردین مشکل رو حل نکرد، ولی استتوس‌بارم رو خوشگل‌تر کرد! ممنونم! :smiley: 
@rastikerdar تو تست کردن فرمتی که شما دادین متوجه شدم، تغییر دادن فرمت هم باعث میشه تاریخ درست نشون داده بشه و نیاز نیست فعال/غیرفعالش کنم! به هر حال اینم میتونه راه‌حل سریعی باشه! :wink: 

پ.ن: من ادب این مخزن رو نمیدونم به چه شکله که ایشو باید باز بمونه تا اونر ببنده یا خودم ببندم. به هر حال الان که مشکل از اکستنشن نیست، به نظر وجود این ایشو محلی از اعراب نداره و خودتون اگه صلاح میدونید، ببندید.

**Comment by omid** [comment]
آقا هر جور راحتی.
اگه مشکلی نداشتی می‌بندی.

به هر حال فکر کنم این مشکل تا حدودی توی گنوم ۳٫۳۰ حل شده
![screenshot from 2018-10-17 20-09-47](https://user-images.githubusercontent.com/45714/47107040-75c31e80-d248-11e8-9072-064659827bd8.png)

خودم رو خفه کردم، هزار تا افزونه عریض نصب کردم که ببینم الان چطوری می‌شه!

یک نکته دیگه اینکه، اگر افزونه رو به روز کنی، می‌تونی جای نمایش تاریخ رو تعیین کنی. فکر کنم اگر بذاری وسط، این مشکل رو نداشته باشی، چون معمولن اون وسط کمتر چیزی هست!

@rastikerdar شما هم که به روز نکردی که؟ :smiley:

**Comment by omid** [comment]
آخ ببخشید، نسخه آخر هنوز ریویوو نشده و توی سایت گنوم نیست! :-(

**Comment by omid** [comment]
این شکلی خواهد بود

![Uploading Screenshot from 2018-10-17 20-17-31.png…]()

**Comment by meysampg** [comment]
ایول! این ویژگی بهش اضافه شده باشه محشر میشه! دقیقا چیزیه که بهش احساس نیاز هم می‌کردم! دمت گرم آقا! :heart:
