### ISSUE TITLE
عدم شناسایی extension

### ISSUE THREAD

**Issue by mkalantar** [omid/Persian-Calendar-for-Gnome-Shell#20]
بعد از بروزرسانی مخزن، تقویم از لیست اکستنشن‌های گنوم‌شل حذف میشه و نمایش هم داده نمی‌شود.
تا قبل از این کامیت مشکلی نیست.
Commit 5ae6f8e6eabbb41917ee73e362176f1a50cd5eb1
GNOME Shell 3.22.3

**Comment by omid** [comment]
سلام،

چه لینوکسی و چه نسخه‌ای دارید؟
من فکر کنم ۲-۳ سال پیش این نسخه از گنوم رو داشتم!

و این نسخه‌ای که شما نصب کردید، اصلن گنوم ۳٫۲۲ رو [ پشتیبانی نمی‌کنه](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/blob/5ae6f8e6eabbb41917ee73e362176f1a50cd5eb1/PersianCalendar%40oxygenws.com/metadata.json)!

**Comment by mkalantar** [comment]
Debian Jessie

**Comment by omid** [comment]
احتمالن منظورت «استرچ»ه

اما به هر حال، من خیلی وقته که نسخه گنوم ۳٫۲۲ رو پشتیبانی نمی‌کنم.
یعنی نسخه ۵۱ آخرین نسخه بود. بعد از اون یه سری قابلیت‌ها درست کار نمی‌کردند و پشتیبانی حذف شد.
آخرین نسخه ۶۲ است.

دو تا راه دارید به نظرم:
۱- مخازن «ناپایدار» دبیان رو فعال کنید. تا آخرین نسخه گنوم رو داشته باشید
۲- نسخه رسمی و اصلی تقویم فارسی گنوم رو نصب کنید. خودتون توش تغییرات ندید
