### ISSUE TITLE
اظافه شدن تقویم جلالی به تقویم اصلی ابونتو

### ISSUE THREAD

**Issue by imanmoghimiq30** [omid/Persian-Calendar-for-Gnome-Shell#22]
سلام 
ممنون بابت این افزونه کاربردی 
می خواستم بدونم چرا نمیشه از تاریخ شمسی در تقویم اصلی سیستم عامل استفاده کرد یعنی بشه تاریخ ایجاد و تغییر فایل ها رو به شمسی دید
ایا امکانش هست که این افزونه این کار رو بکنه؟

**Comment by omid** [comment]
سلام،
چون تاریخ فایل با روش دیگه‌ای محاسبه و نمایش داده می‌شه.
در حقیقت گنوم‌شل یک برنامه مجزاست و ربطی به گنوم فایلز(ناتیلوس) نداره.
هم زبون برنامه‌نویسی اون متفاوته و هم پروژه متفاوتی است و هم ممکنه به راحتی نشه براش پلاگین نوشت، در نتیجه باید سورس اصلی برنامه تغییر کنه که می‌تونه شرایط رو پیچیده‌تر بکنه.
در نهایت هم همه این‌ها ربطی به نحوه نمایش تاریخ در مثلن شل نداره.

برای اطلاعات بیشتر می‌تونید پروژه گنوم فایلز رو بررسی کنید:
https://github.com/GNOME/nautilus
