### ISSUE TITLE
Bug on Show Calendar

### ISSUE THREAD

**Issue by nimadeve** [omid/Persian-Calendar-for-Gnome-Shell#23]
Hi , After Update Manjaro linux , calendar can not show date and another thing , Please Fix it

**Comment by tahajahangir** [comment]
The current version of extension is not compatible with new Gnome 3.32. Then extension space on tab bar is converted to a larger blank space, and also many characters displayed as 3-dots .

![Screenshot from 2019-08-04 12-17-21](https://user-images.githubusercontent.com/815585/62421163-a890b300-b6b2-11e9-8082-d04ca34177df.png)

**Comment by morealaz** [comment]
I use Arch with latest version of extension installed from GitHub and it worked without any such problem. Maybe its related to something else, especially your system font setting. Have you try installing a good Persian font like **Vazir** or something else? Although extension worked with all fonts with Arabic and Persian support.

**Comment by Miladdarren** [comment]
Same problem here on manjaro gnome 3.32

**Comment by omid** [comment]
I also saw this problem. It looks like a Gnome issue.
Can you tell me the exact version of Gnome?
I have this in Arch: 1:3.32.2+11+g1c6abf378-1

Why don't you see this issue with other extensions? Because we are using a custom woff font (@morealaz FYI) which is Vazir.

**Comment by omid** [comment]
I forgot to mention, it shows Squares and dots ("...") to me.
Instead of empty blocks in @tahajahangir's picture, square blocks!

**Comment by omid** [comment]
I tried it by removing the custom font (Vazir), and it works fine after that. But again ugly :face_with_head_bandage:

**Comment by omid** [comment]
Please try the git version... and tell me if it is fine or not. Thanks :-)

**Comment by nimadeve** [comment]
Yeah Fixed , Well done ! 
Thanks
