### ISSUE TITLE
عدم نمایش اعداد و تاریخ

### ISSUE THREAD

**Issue by BahramShahraki** [omid/Persian-Calendar-for-Gnome-Shell#24]
با درود بر شما،خواستم خدمت شما عرض کنم که این افزونه اعداد و تتاریخ رو نشون نمیده البته قبلا به خوبی کار میکرد. من از منجارو لینوکس ۱۸.۰۴ استفاده میکنم و ورژن گنوم ۳.۳۲.۱ هست. از زحمات شما سپاسگزارم

**Comment by omid** [comment]
سلام، ممنون.
قبلن گزارش شده و برطرف شده.
نسخه گیتهاب درسته الان، اما سایت گنوم.اکستنشنز هنوز تغییرات رو تایید نکرده :-(
