### ISSUE TITLE
خراب شدن فونت در آپدیت جدید مانجارو

### ISSUE THREAD

**Issue by kam2yar** [omid/Persian-Calendar-for-Gnome-Shell#25]
فونت ها به صورت دو سفید و ناخوانا نمایش داده میشن

**Comment by omid** [comment]
سلام، ممنون.
قبلن گزارش شده و برطرف شده: #23
نسخه گیتهاب درسته الان، اما سایت گنوم.اکستنشنز هنوز تغییرات رو تایید نکرده :-(

**Comment by kam2yar** [comment]
خیلی ممنونم از پلاگین عالیتون 
فیکس شد
