### ISSUE TITLE
Order is reversed

### ISSUE THREAD

**Issue by danialbehzadi** [omid/Persian-Calendar-for-Gnome-Shell#26]
In Persian locale, the order of days and controls of calendar are reversed (ltr).

![عکس‌صفحه از 2019-09-07 10-13-07](https://user-images.githubusercontent.com/3658678/64470451-7ef3fd00-d132-11e9-9ddb-14b772ef1059.png)

**Comment by omid** [comment]
@danialbehzadi is this still a problem?

**Comment by danialbehzadi** [comment]
Yes, tried the latest version on GNOME 40 on Fedora: 
![نماگرفت از 2021-07-06 07-16-09](https://user-images.githubusercontent.com/3658678/124591981-3282c100-de72-11eb-9255-48a32ff59d25.png)

**Comment by omid** [comment]
There will be a new version soon, please check with that too. Thanks.

**Comment by omid** [comment]
So I'll close it, if it's still there, please reopen it.

**Comment by danialbehzadi** [comment]
It's fixed
