### ISSUE TITLE
Stopped working in the latest update of Ubuntu 19.10

### ISSUE THREAD

**Issue by habibseifzadeh** [omid/Persian-Calendar-for-Gnome-Shell#30]
Dear Omid,

Thanks for your useful widget. It worked perfectly in Ubuntu 19.10, but it has disappeared after the latest update since a couple of days ago. 

Cheers,
Habib

**Comment by omid** [comment]
Hey,

Are you sure it's installed? Go to Gnome Tweaks and check it.
If it is installed, press CTRL+R and then type "lg" and enter, go to "Extentions" tab and then find the extension and see errors.

**Comment by habibseifzadeh** [comment]
You're right,

The problem was that the Gnome extensions had been disabled as a whole. I don't know why but after enabling it, the extension works like before.

Thanks for your help
