### ISSUE TITLE
Incompatibility with GNOME shell 3.36

### ISSUE THREAD

**Issue by danialbehzadi** [omid/Persian-Calendar-for-Gnome-Shell#32]
Extension is incompatible with GNOME shell 3.36 (and 3.35)

**Comment by omid** [comment]
Have you tried the really latest version which I released last night?
It's working with 3.36, but still has some bugs.

**Comment by danialbehzadi** [comment]
No. I  justremoved it and installed from GNOME extensions a couple of minutes ago.

**Comment by omid** [comment]
It's working for me on Ubuntu 20.04 with gnome-shell 3.35.91.
Anyhow, I pushed some new changes, which are not reviewed/published yet, which may fix your case.

If not, tell me exactly your setup, then I may be able to reproduce it.

**Comment by omid** [comment]
Now I'm using Gnome 3.36 on Arch and it's working.
Do you still have problem?

**Comment by omid** [comment]
@danialbehzadi any news?

**Comment by danialbehzadi** [comment]
Fixed
