### ISSUE TITLE
Problem with Gnome 3.34

### ISSUE THREAD

**Issue by fakhamatia** [omid/Persian-Calendar-for-Gnome-Shell#33]
سلام
وقتی افزونه رو نصب میکنم خطا میده و نصب نمیشه
ولی تقویم بقل ساعت میاد
ولی تو ریستارت بعدی میره 

Ubuntu 19.10
Gnome 3.34.2

**Comment by omid** [comment]
سلام،

می‌تونید افزونه رو یک‌بار حذف کنید و دوباره نصب کنید؟
نتیجه رو بهم خبر بدید.

ممنون

**Comment by fakhamatia** [comment]
تغییری انجام دادید؟
درست شد
من چند بار امتحان کرده بودم

**Comment by omid** [comment]
آره، اشتباه من بود.

نسخه‌ای رو برای گنوم ۳٫۳۶ منتشر کرده بودم که سازگاری با ۳٫۳۴ نداشت و من بعدن فهمیدم و یادم رفت غیرفعالش کنم.

امروز رفتم و اون رو غیرفعال کردم و تا جایی که می‌دونم تنها راهش اینه که افزونه رو حذف و نصب کنید تا درست بشه. چون یه جورایی دانگرید حساب می‌شه.

خوب خوبه که مشکل برطرف شد، اگر همه چیز آرومه، تیکت رو ببندید لطفن :-)
