### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by farmani** [omid/Persian-Calendar-for-Gnome-Shell#34]
hey bro :)

I just install the extension on a new installed ubuntu 18.04 extension couln't load and journal contain this error log

> Mar 13 09:15:35 hero gnome-shell[1969]: Extension "PersianCalendar@oxygenws.com" had error: TypeError: this.add_actor is not a function

is there any tweak or things I can do? IMO some recent changes break the code

**Comment by omid** [comment]
Hi dude :>

Could you please remove the extension and install it again?
You can follow the reason here:
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/33

**Comment by farmani** [comment]
@omid actually it was the recent version and I tried again, same error:

gnome version 3.28.2

**Comment by omid** [comment]
3.28.2 :confused:  Isn't it too old?! :smiley: 
Anyhow, did you install it recently?

Can you send the version inside the metadata.json file, please? For your gnome-shell version, it should be 65 at most. But I think you've 68 which is wrong!

If you have higher than 65, then it's a gnome-shell bug or the way you install this addon is not correct.

**Comment by farmani** [comment]
yes, I just install it a day ago and yes ubuntu lts 18.04 gnome shell a bit old.

hmm yes here is the content of metadata.json

`{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Shows Persian date in the top panel.\n\nIt shows:\n1- Persian calendar\n2- It can show, today is holiday or not!\n3- Show notification onDayChanged!\n4- Date converter between Persian, Gregorian and Lunar Hijri\n5- Events:\n5-1- Official solar events.\n5-2- Official lunar events.\n5-3- Official international events.\n5-4- Traditional Persian events.\n5-5- Persian personages.\n\nPlease \"rate\" here and \"star\" project in GitHub.\nPlease open an issue in GitHub if you found something or have an idea!",
  "name": "Persian Calendar",
  "original-authors": "Omid Mottaghi Rad",
  "shell-version": [
    "3.36"
  ],
  "url": "https://github.com/omid/Persian-Calendar-for-Gnome-Shell",
  "uuid": "PersianCalendar@oxygenws.com",
  "version": 69
}`

hmm issue was the version and checking out to `ddaf0b6` and rebuild resolve the issue.

thanks for your help. and I think that would be a good idea to use tag and release each version so they are separately accessible :)

it's a great work and thanks for your time and efforts.

**Comment by omid** [comment]
If you are using old gnomes, why don't you install it via the official website?

And you're welcome to create a PR ;-)
