### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by SCR-IR** [omid/Persian-Calendar-for-Gnome-Shell#48]
با سلام
درخواست‌هایی برای اِعمال تغییرات، ثبت شد.
اگر بتوانید بر نسخه‌ی 3.30 نیز اِعمال بفرمایید، بسیار عالی خواهد شد.
چراکه توزیع اصلی دبیان، از گنوم 3.30 استفاده می‌کند و تا سال 2021 ادامه خواهد داشت.

لینک فایل‌های سازگار برای گنوم 3.30.2:
[http://up.iranblog.com/uploads/PersianCalendar-oxygenws-com.7z](http://up.iranblog.com/uploads/PersianCalendar-oxygenws-com.7z)

فقط کافیست جایگزین نمایید تا کاربران گنوم 3.30 نیز بهره‌مند شوند.

**Comment by omid** [comment]
سلام،

ممنون. نظرهایی دادم که خوشحال می‌شم تصحیح کنید.
ضمن اینکه تمایل دارم تقویم‌ها تا حد ممکن براساس موضوع دسته‌بندی بشن توی فایل‌های مختلف که قابل فعال و غیرفعال کردن باشند.
و عناوین وقایع حتی‌الامکان خلاصه‌سازی بشن، چون از نظر ظاهری کل ساختار تقویم و نوتیفیکیشن‌ها رو تحت تاثیر قرار می‌دن.

در ضمن، ممنون می‌شم یک پی.آر. بسازید که راحت‌تر بشه پیگیری کرد. یا حداقل در هر مورد یک پی.آر. بسازید.

موفق باشید.

**Comment by SCR-IR** [comment]
مناسبت‌های رسمی کشور، به سه‌نوع وابسته به تاریخ‌های 1- شمسی 2- قمری 3- میلادی ، تقسیم می‌شوند.

در این ساختار جدید، سه فایل
iranSolar
iranLunar
world
را به مناسبت‌های رسمی کشور، اختصاص داده‌ایم که مصوّب ش.ع.ا.ف و ابلاغ‌شده هستند. مناسبت‌های رسمی را نمی‌توان حذف کرد یا با غیررسمی‌ها مخلوط نمود؛ چراکه ابلاغیه‌ی دولتی دارند و اینکار موجب بی‌اعتبارشدن نرم‌افزار و مغایرت با تقویم رسمی کشور می‌شود.

فایل مربوط به شخصیت‌های ایرانی، اگر تکمیل شود، عالیست؛ امّا باید از همپوشانی با فایل
iranSolar
جلوگیری کرد که اکنون همپوشانی بسیار بالا داشت(تکرار) و به‌همین‌دلیل، آن‌را حذف کردیم.

مناسبت‌های ایران باستان نیز بهتر است بازنگری شوند و موارد غیرموثّق و همچنین همپوشانی‌ها حذف گردند. علاوه‌برآن، امروزه 99 درصد مردم، استفاده‌ی خاصی از این مناسبت‌ها ندارند و بهتر است پیشفرض غیرفعال باشند.

**Comment by omid** [comment]
این تقویم صرفن برای کشور ایران ساخته نشده.
به عنوان مثال فایل «ورلد» برای وقایع تعیین شده توسط یو.ان. ایجاد شده و مستقیمن ربطی به ایران نداره. اما توی تغییرات شما تمام این ساختار به هم ریخته شده.

مناسبت‌های رسمی کشور ایران رو در صورتی می‌شه قرار داد، که بشه فعال و غیرفعالشون کرد.
بسته به نوع مناسبت. می‌شه حتا نوع مناسبت رو به ایوینت‌ها اضافه کرد و توی تنظیمات بشه این مقادیر رو تغییر داد.
مثلن برای ولادت زرتشت، نوع ایران باستان و برای ولادت حضرت علی، نوع اسلامی و روز ۱۳ آبان نوع انقلابی یا همچین چیزی.

در نهایت می‌شه همیشه تمام تقویم رو خوند و تعطیلات رو نشون داد، اما وقایع دسته‌بندی‌های غیرفعال نمایش داده نشه.

در نهایت، اعمال سلیقه شخصی توی فعال یا غیرفعال بودن پیش‌فرض قابلیت‌ها رو همونطور که گفتم صلاح نمی‌دونم. منبع هم ذکر کردم در داخل فایل‌ها.
ضمن اینکه اعلام مابقی مناسبت‌ها هم «استفاده» ای برای کسی نداره، پس همه غیرفعال باشند!

**Comment by omid** [comment]
مجدد هم تاکید می‌کنم، یک پی.آر. بسازید، در غیر این صورت نمی‌تونم تست یا تایید کنم.

**Comment by msm1365** [comment]
اعمال سلیقه در مورد تقویم اصلا کار درستی نیست
اما سلایق اگر به صورت آپشن در دسترس باشند گزینه خوبیه.
اگر بخواهیم تقویم خورشیدی به صورت یکپارچه همراه با گنوم عرضه بشه باید حرفه ای تر با این موارد برخورد بشه
