### ISSUE TITLE
i3 openbox DMs

### ISSUE THREAD

**Issue by azadpsg** [omid/Persian-Calendar-for-Gnome-Shell#50]
Dear maintainer du to your shell extension is really great would you please improve it in in a way that could be useable in i3 or Openbox desktop environments?

or if there is an easy way guide me

Thanks again

Aza:D

**Comment by omid** [comment]
Hey,

Oops, I don't think it's easily possible.
It's highly coupled to Gnome.

**Comment by azadpsg** [comment]
sad news :(

any tips that I could help ...?

**Comment by omid** [comment]
Help in general or in the case of i3/openbox integration?

If you're talking in general, then there are several issues that we can solve.
One of the main ones I think is fixing lunar days:
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/11
