### ISSUE TITLE
تنظیمات باز نمی‌شه

### ISSUE THREAD

**Issue by aasadeghi** [omid/Persian-Calendar-for-Gnome-Shell#52]
سلام. تنظیمات از داخل خود اکستنشن باز نمی‌شه و این ارورو می‌ده:
Execution of "gnome-extensions prefs" failed: command not found

البته از ترمینال می‌تونم با این دستور بازش کنم:
gnome-extensions prefs PersianCalendar@oxygenws.com
و کار هم می‌کنه تنظیماتش

Extension version: 69
Ubuntu version: 20.04
Gnome shell version: 3.36

**Comment by omid** [comment]
سلام،
درست می‌گی، یکی از دوستان [درستش کرده](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/pull/51) و من یادم رفته منتشر کنم.

الان برای سایت فرستادم...  به زودی نسخه جدید در دسترس قرار می‌گیره.

لطفن بعد از تست اگر اوکی بود، تیکت رو ببندید.
موفق باشید

**Comment by sadeghi-aa** [comment]
آره این ورژنی که اینجا هست رو دستی نصب کردم و اوکی بود.
ممنون

**Comment by omid** [comment]
به زودی توی سایت رسمی گنوم‌شل هم میاد. وقتی تایید بشه!
