### ISSUE TITLE
ناقص شدن نمایش تاریخ

### ISSUE THREAD

**Issue by safuxingdi** [omid/Persian-Calendar-for-Gnome-Shell#54]
سلام.
امروز به یک باره تاریخ به این شکل نمایش داده میشه.
نه تنظیمات اکستنشن رو دستکاری کردم و نه تنظیمات خود صفحه.

![Screenshot from 2020-07-29 22-49-04](https://user-images.githubusercontent.com/68774806/88839564-801d9500-d1f0-11ea-9b67-816509feeda7.png)

**Comment by omid** [comment]
سلام،
مشکل حل شد؟ :)

**Comment by safuxingdi** [comment]
آره فرداش خود به خود درست شد :)
تا امروز هم دیگه تکرار نشد همچین چیزی.
مطمئن نیستم مشکل از چی بود.

**Comment by omid** [comment]
این یک باگ گنوم‌شل بوده که فکر کنم توی آخرین نسخه‌ها برطرف شده، فقط بعضی اوقات ممکنه پیش بیاد!
