### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by mehrdadashtari** [omid/Persian-Calendar-for-Gnome-Shell#55]
سلام الان که همه ی سیستم ها به اینترنت متصل هستند پیشنهاد میکنم ارتباط با ای پی آي های تقویم رو هم در این برنامه ی خوب پیاده سازی کنید

خودم از این سرویس استفاده میکنم: https://apieco.ir/api/farsicalendar/

 اطلاعات خوبی میده مثل رویداد های هر روز و تبدیل تاریخ به شمسی و قمری و میلادی

**Comment by omid** [comment]
سلام،

بسیار عالی.

اما چند نکته داره به نظرم.

- توسعه‌دهنده مشخص نیست
- پروژه بازمتن نیست
- داکیومنت ضعیفی داره، به عنوان مثال، غلط املایی داره یا اینکه اصلن مشخص نیست موضوع یعنی چی! یا از مقادیر غیراستاندارد استفاده کرده، مثل prs؟!
- وقایع لیست شده مشخص نیست چیا هستند، ممکنه وقایع بی‌خود توشون زیاد باشه

در مجموع اعتبار بالایی نداره به نظرم، وقت بذاری و اینگریتش کنیم و آخر سر...

ضمن اینکه نمی‌دونم سر اون ای.پی.آی.کی چی میاد وقتی توی سورس کد قرار بگیره و برای همه ارسال بشه. اگر هم هر کس خودش بخواد یکی بسازی و توی تنظیمات برنامه بذاره، اکثریت مردم این کار رو نمی‌کنند!

کما اینکه بودن همچین چیزی شدیدن خوبه و به کار میاد، اما با وضع فعلی ای.پی.آی نظرم مثبت نیست بهش.

**Comment by omid** [comment]
البته الان اینجا پیداشون کردم که تعدادی از نکاتی که گفتم رو پاسخ داد:

https://farsicalendar.com/

**Comment by omid** [comment]
ممنون، خوب چه تفاوتی وجود داره اگه مسقیم از ای.پی.آی اصلی اسفاده کنیم یا از طریق سایت شما؟

**Comment by mehrdadashtari** [comment]
@omid سلام امیدوارم که حالت خوب باشه

سایت ما بازاریه برای معرفی و فروش ای پی آی ها. برنامه نویسان معمولا بیش از یک وب سرویس مورد نیازشون هست و ما سعی کردیم تا این پکیج رو به کامل ترین شکل در اختیارشون بذاریم.

 از مزیت ها میتونم به صدور یک توکن برای فراخوانی تمام ای پی آی هایی که به صورت رایگان یا غیر رایگان دارید استفاده میکنید اشاره کنم. در استفاده از سرویس های تجاری هم تنها یک فاکتور در انتهای ماه براتون ایجاد میشه و لازم نیست در سایت های مختلف حساب کاربری داشته باشید یا نگران پرداخت در تک تک اون سایت ها باشید.

در حال حاضر برنامه نویسان زیادی در سایت فعال هستند، بستری فراهم شده تا برنامه نویسان تمام نیاز هاشون رو برطرف کنند و با استفاده از این سرویس ها محصولشون رو توسعه بدن یا حتی سرویس جدیدی بسازند.

در ضمن این رو هم بگم که ای پی آی ها زیر نظر ارائه دهنده ی سرویس در اپی اکو منتشر شده و حقوق معنوی محصول کاملا رعایت شده و فقط مسئولیت کیفیت سرویس برعهده ی ماست.

باعث افتخار ما خواهد بود که شما، بعنوان یکی از برنامه نویس های سرشناس از پلتفرم اپی اکو استفاده کنید.

سوالی داشتید بنده در خدمتتون هستم

**Comment by omid** [comment]
تیکت بسته می‌شه چون سایت پیشنهادی دیگه در دسترس نیست!
