### ISSUE TITLE
امکان تغییر الفبای عربی به لاتین

### ISSUE THREAD

**Issue by ariyadey** [omid/Persian-Calendar-for-Gnome-Shell#58]
من مکان نماد تقویم رو در وسط پنل کنار تقویم خود گنوم استفاده میکنم. برای یکدستی بیشتر در ظاهر محیط، پیشنهاد میکنم به کاربر امکان بدید از الفبای لاتین هم بتونه در پنل استفاده کنه.
اسامی ماه ها رو هم اگه با الفبای لاتین اضافه کنید خیلی عالی میشه. اونوقت دیگه اصلا حس نمیشه که این یک افزونه است و کاملا یکدست بنظر میاد.

**Comment by ariya-mms** [comment]
![Screenshot from 2020-08-24 16-29-45](https://user-images.githubusercontent.com/41640086/91042858-bc91b480-e627-11ea-9fc1-b7b34ebeed55.png)

**Comment by ariya-mms** [comment]
![Screenshot from 2020-08-24 16-35-32](https://user-images.githubusercontent.com/41640086/91042955-e3e88180-e627-11ea-9bbc-27ec4d683a44.png)

**Comment by omid** [comment]
منظورت اینه که مثلن بنویسه:

3 Shahrivar - Doshanbe?

**Comment by ariya-mms** [comment]
آره ولی دوشنبه رو Monday بنویسه نه Doshanbeh.

**Comment by omid** [comment]
کار زیاد سختی نیست، اما واقعن چقدر نیازش وجود داره؟
چند نفر توی دنیای واقعی این نیاز رو دارند؟

خوبه مثلن اگر این تیکت ۱۰ تا تامبزآپ بگیره انجام بدیم؟

**Comment by ariya-mms** [comment]
آره فکر خوبیه :)

**Comment by mfat** [comment]
پیشنهاد خوبیه لطفا اضافه کنید. شیک تر میشه. هم این و هم امکان تغییر فونت فارسی.

**Comment by omid** [comment]
با تغییرات خیلی خوبی که @eshagh79 عزیز داره توی [پشتیبانی چندزبانگی](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/pull/103) ایجاد می‌کنه، خیلی راحت‌تر می‌شه این قابلیت رو به سیستم اضافه کرد.
