### ISSUE TITLE
تفاوت رنگ روز تعطیل با روزهای ماه‌های دیگر

### ISSUE THREAD

**Issue by ariyadey** [omid/Persian-Calendar-for-Gnome-Shell#59]
برای پیدا کردن بهتر روزهای تعطیل، لطفا رنگ دو مورد یاد شده در عنوان رو از هم تغییر بدید.
![Screenshot from 2020-08-24 16-29-45](https://user-images.githubusercontent.com/41640086/91042661-615fc200-e627-11ea-855e-6a775bcfc5cf.png)

**Comment by omid** [comment]
سلام،

منظورت چیه؟ نفهمیدم

**Comment by ariya-mms** [comment]
الآن تو تصویر بالا، رنگ روز ماه آینده (یعنی مهر) خاکستریه. رنگ روزهای تعطیل هم همینطور.
اینجوری یکم سخت‌تر میشه روزهای تعطیل رو زود پیدا کرد.

چون هر کسی از تم متفاوتی میتونه استفاده کنه فکر نکنم با تغییر رنگ بشه مشکل رو حل کرد. (من خودم همین الآن میبینم که رنگ روزهای ماه مهر یه کوچولو تیره تر از روزهای تعطیله). 

پس راه بهتر اینکه با کاری بجز دستکاری رنگ مثل بولد کردن روزهای تعطیل یا هرکار دیگه‌ای که خودت صلاح میدونی این دو رو از هم تفکیک کنی.

**Comment by omid** [comment]
من دخل و تصرفی تو اونا ندارم، از تم گنوم‌شل استفاده می‌کنم.
اگه دقت کنید خود تقویم گنوم هم همین‌شکلیه.

(البته اگر تطابقی با تقویم اصلی گنوم‌شل نداره، این باگ محسوب می‌شه و ممنون می‌شم گزارش کنید و باید برطرف بشه)

**Comment by SCR-IR** [comment]
اگر رنگ‌ها تغییر کنند، واضح‌تر میشه. البتّه در آن‌صورت باید رنگ پس‌زمینه هم تغییر کنه.
بهتره به‌عنوان یک آپشن در بخش تنظیمات قرار بگیره.

![نمونه](https://raw.githubusercontent.com/SCR-IR/Tmp/main/pic/jalali.jpg)

**Comment by omid** [comment]
موافقم، میشه یک آپشن اضافه برای اوررایت کردن رنگ گذاشت.
مثل چیزی که برای رنگ متن داخل نوار بالا (یا پایین!) داریم.

**Comment by medicamin** [comment]
As a workaround not a solution, just add `color: #f57f91` to the line `.calendar-nonwork-day` in the stylesheet.css

**Comment by omid** [comment]
<div dir="rtl">
فعلن موقتن رنگ روزهای تعطیل رو همونی که @medicamin انتخاب کرده بود گذاشتم.

تا اینکه اون گزینه‌ی انتخاب رنگ به تنظیمات اضافه بشه
</div>

**Comment by omid** [comment]
<div dir=rtl>@ariyadey 

این آپشن اضافه شد.
توی تصویر جدیدی که آپلود کردم می تونید ببینید.
</div>
