### ISSUE TITLE
عدم پشتیبانی نسخه‌ی «جاری» گنوم

### ISSUE THREAD

**Issue by SCR-IR** [omid/Persian-Calendar-for-Gnome-Shell#60]
پشتیبانی از نسخه‌های قدیمی‌تر گنوم حذف شده، درصورتی‌که این عمل باید با توجّه به نسخه‌ی جاری گنوم در توزیع پایه‌ی «**دبیان**» تنظیم شود، نه اوبونتو!

اکنون نسخه‌ی گنوم‌شل در آخرین انتشار دبیان، **3.30.2** می‌باشد. بهتر است قطع پشتیبانی‌ها، هر ۲سال یکبار، بعد از انتشار نسخه‌ی جدید دبیان انجام گردد.

[https://distrowatch.com/table.php?distribution=debian](https://distrowatch.com/table.php?distribution=debian)

**Comment by omid** [comment]
چرا «**باید**» ربطی به توزیع دبیان داشته باشه؟
گنومی که برای دو سال پیشه، افزونه‌های احتمالن دو سال پیش باید روشون نصب بشه.

به هر حال، راه حل این مشکلی که بیان می‌کنید، اینه که گیت، تگ (لیبل) بخوره.
ممنون می‌شم همت کنید و این روند رو در اسکریپت ریلیز که توی ریشه پروژه هست پیاده‌سازی کنید.

در این مورد مختصری اینجا صحبت شده:
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/34

**Comment by SCR-IR** [comment]
در تغییراتی که درخواست آن ارسال شد، مشکل برای نسخه‌های قدیمی‌تر گنوم برطرف گردیده و در نسخه‌های زیر نیز با موفّقیت تست شد:
debian - Gnome 3.14
debian - Gnome 3.30
ubuntu - Gnome 3.36
