### ISSUE TITLE
نیاز به یک شاخه‌ی جداگانه

### ISSUE THREAD

**Issue by SCR-IR** [omid/Persian-Calendar-for-Gnome-Shell#61]
لطفاً تغییراتی که در مخزن محلّی خودتان (روی رایانه‌ی شخصی) در حال انجام است و هنوز با مخزن گیت‌هاب ادغام نشده را در یک شاخه‌ی جداگانه در اینجا قرار دهید تا درصورت مشارکت دیگران، بعداً تداخل‌های کمتری وجود داشته‌باشد.
"develop" branch

**Comment by omid** [comment]
من معمولن چیزی که استیبل نشده نمی‌فرستم بالا.
البته این فارغ از باگ‌هایی است که خوب وجود داشتند و دارند.
