### ISSUE TITLE
امکان تغییر فونت

### ISSUE THREAD

**Issue by mohamad-norouzi** [omid/Persian-Calendar-for-Gnome-Shell#64]
خیلی بهتر میشد اگه توی تنظیمات این امکان رو داشتیم که از خود پاپ‌آپ گنوم فونت رو انتخاب می کردیم.
![image](https://user-images.githubusercontent.com/8435784/93260497-bcb04a80-f7b6-11ea-96dd-e7e405f0168a.png)

**Comment by omid** [comment]
این خیلی شبیه این تیکته، آره؟
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/10

توی برخی کامنت‌ها به همچین قابلیتی اشاره شده به نظرم.

**Comment by mohamadnorouzi20** [comment]
@omid بله
اضافه شدن دکمه اون پاپ‌آپ هر ۲ مشکلو حل می کنه
