### ISSUE TITLE
GNOME broke it again 🤦🏻‍♂️

### ISSUE THREAD

**Issue by danialbehzadi** [omid/Persian-Calendar-for-Gnome-Shell#65]
After upgrading to GNOME shell 3.38, the extension does not load, giving an ERROR badge.

**Comment by omid** [comment]
Can you give me a link to an iso of a distro with the 3.38 version plz?

**Comment by danialbehzadi** [comment]
http://cdimage.ubuntu.com/daily-live/current/groovy-desktop-amd64.iso

**Comment by omid** [comment]
It should be fixed in github. (will be released when they review it!)

**Comment by omid** [comment]
@danialbehzadi, if you think everything is fine, plz close the issue.

**Comment by danialbehzadi** [comment]
No. There's still error…

**Comment by omid** [comment]
What is the error now?

You can find it by running:
`sudo journalctl -f -g PersianCalendar@oxygenws.com`

**Comment by danialbehzadi** [comment]
Fixed after logging out and in again.
