### ISSUE TITLE
Error updating extension in 3.36.4 gnome shell

### ISSUE THREAD

**Issue by artmarydotir** [omid/Persian-Calendar-for-Gnome-Shell#66]
thank you for the great extension , cant be update with the GNOME Shell 3.36.4

![Screenshot from 2020-10-03 08-15-43](https://user-images.githubusercontent.com/11363931/94983551-a9400600-0550-11eb-8f7a-6f966db601f8.png)

**Comment by omid** [comment]
Thanks :)

Can you run the following command and tell me the result?
`sudo journalctl -f -g PersianCalendar@oxygenws.com`

I have 3.36.6 and it works!

**Comment by saeedesmaili** [comment]
I have the same problem and here is the error:

```
JS ERROR: Extension PersianCalendar@oxygenws.com: Error: A different version was loaded previously. You need to log out for changes to take effect.
                                                 loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52
                                                 callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
                                                 gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**Comment by saeedesmaili** [comment]
I tried [logging out of the gnome extension account](https://extensions.gnome.org/accounts/logout/) and tried installing again, but I still see the error.

**Comment by artmarydotir** [comment]
here is the output:
```

Oct 03 12:44:01 : JS ERROR: Extension PersianCalendar@oxygenws.com: Error: A different version was loaded previously. You need to log out for changes to take effect.
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52
                                                  callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
                                                  gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

```

**Comment by omid** [comment]
It doesn't look like an extension problem!
Can you completely remove/uninstall it and reinstall?
And maybe reboot the system :thinking: (feels like Windows!)

**Comment by saeedesmaili** [comment]
I uninstalled and installed again, but it didn't help.

**Comment by omid** [comment]
Which distro you are using... then I can test it on my own!

**Comment by saeedesmaili** [comment]
Ubuntu 20.04

**Comment by omid** [comment]
Did you reboot also?

**Comment by saeedesmaili** [comment]
Not yet. I don't think it can fix.

**Comment by omid** [comment]
I read it in some other projects. It may fix it. Please try that and report.

**Comment by artmarydotir** [comment]
> Which distro you are using... then I can test it on my own!

Ubuntu 20.04.1 LTS

I also uninstall and install again. but it did not work

**Comment by omid** [comment]
@artmarydotir & @saeedesmaili, please report the result after a reboot.

**Comment by artmarydotir** [comment]
>please report the result after a reboot.

i just reboot and its work. thank you,🙏
im closing this issue .
