### ISSUE TITLE
اشکال بعد از بروز رسانی در ابونتو

### ISSUE THREAD

**Issue by mjahmadi** [omid/Persian-Calendar-for-Gnome-Shell#67]
سلام
خیلی ممنون بابت کار مفیدتون

متاسفانه بعد از بروز رسانی اخیر دیگه روی ابونتو 20.04 کار نمی کنه و خطا میده
لطفا بررسی کنید.

**Comment by omid** [comment]
سلام،

یک بار ریبوت کنید.

#66

**Comment by omid** [comment]
اگر مشکل حل شده، لطفن ایشو رو ببندید

**Comment by hamid255** [comment]
سلام.
در زمان به‌روزرسانی خطا می‌ده، اما بعد از دوباره لاگین کردن مشکل رفع می‌شه.
به نظرم هنوز هم باگ محسوب میشه، به خصوص که هر دفعه وقتی خطا می‌داد، پاکش می‌کردم.
من از فدورای ۳۲ استفاده می‌کنم.
در کل افزونه‌تون عالیه، ممنون.

**Comment by omid** [comment]
سلام،

درست می‌گی در کل... اما گویا این یک باگ نیست و یک فیچره :)
اما در هر صورت ربطی به اکستنشن‌ها نداره و به گنوم مربوطه.

توضیحات این تیکت رو بخون:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1248

‍‍`Spidermonkey caches imports, which means that uninstalling an
old extension version and installing a new one doesn't work as
expected`

این پاسخ به این تیکت هم توضیحات کاملی داده:
https://github.com/mlutfy/hidetopbar/issues/242#issuecomment-696004819

**Comment by mjahmadi** [comment]
امید عزیز بسیار ممنون بابت زحمتی که کشیدی
بله مشکل بعد از ریبوت کردن حل شد
اما احتمالا ری استارت کردن گنوم هم باید کافی باشه که البته من امتحانش کردم

خیلی ممنون
Keep up to good work : )
