### ISSUE TITLE
آیا امکان استفاده از این پکیج در سینمون مینت هست؟

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [omid/Persian-Calendar-for-Gnome-Shell#68]

**Comment by omid** [comment]
تا جایی که می‌دونم، سینمون از گنوم ۲ گرفته شده باشه.
در این صورت این افزونه براش کار نخواهد کرد.

اما ممکنه این یکی که ۱۰۰ سال پیش نوشتم براش کار کنه:
https://github.com/omid/pcalendar

البته اون رو نه توسعه می‌دم و نه هیچ ضمانتی داره که کار کنه یا نه!
