### ISSUE TITLE
تبدیل تاریخ

### ISSUE THREAD

**Issue by amirkaveh** [omid/Persian-Calendar-for-Gnome-Shell#70]
در قسمت تبدیل تاریخ، عنوان «از فارسی» صحیح نیست. بهتر است با «از شمسی» یا «از جلالی» جایگزین شود.

**Comment by omid** [comment]
موافقم

اما بیشتر از اون، با «هجری خورشیدی» و «هجری قمری» موافق‌ترم :)
یا خلاصه‌تر، «هـ.خورشیدی» و «هـ.قمری»

اگر موافقی، یک پول‌ریکوئست بزن خیرش رو ببینی‌ :)

پ.ن: «هجری ماهی» نداریم نه؟ :دی

**Comment by mirmousaviii** [comment]
سوالی که برای من وجود داره اینه که چرا هر سه تا تقویم با دین شروع میشه؟
