### ISSUE TITLE
بروز خطا در زمان باز کردن پنجره تنظیمات

### ISSUE THREAD

**Issue by pk-r** [omid/Persian-Calendar-for-Gnome-Shell#75]
سلام

آقا خیلی ممنونم واقعا کمبود این اکستنشن احساس میشد.

من یه مشکلی دارم که پنجره تنظیمات وقتی باز میشه یک اررور لاگ و استک تریس نیشون میده.

=======SYSTEM INFORMATION===========
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
GNOME_VERSION="3.36.8" 
WINDOWING_SYSTEM="X11"
============ERROR LOG=======================

TypeError: this.main_hbox.append is not a function

Stack trace:
  _init@/home/pouria/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/prefs.js:45:24
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/home/pouria/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/prefs.js:202:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by omid** [comment]
سلام،

اگر از گیت نصب کردید، چون از گنوم ۳.۳۶ استفاده می‌کنید کار نمی‌کنه.
بهتره افزونه رو پاک کنید و از سایت گنوم نصب کنید که سازگاری با نسخه‌های مختلف گنوم رو پشتیبانی می‌کنه.

از یک هفته پیش، پشتیبانی از جی.تی.کی ۳ رو دراپ کردم و از این به بعد فقط با گنوم‌شل ۴۰+ کار خواهد کرد.

**Comment by SCR-IR** [comment]
> سلام،
> 
> اگر از گیت نصب کردید، چون از گنوم ۳.۳۶ استفاده می‌کنید کار نمی‌کنه.
> بهتره افزونه رو پاک کنید و از سایت گنوم نصب کنید که سازگاری با نسخه‌های مختلف گنوم رو پشتیبانی می‌کنه.
> 
> از یک هفته پیش، پشتیبانی از جی.تی.کی ۳ رو دراپ کردم و از این به بعد فقط با گنوم‌شل ۴۰+ کار خواهد کرد.

لطفاً [این فایل](https://github.com/SCR-IR/gnome-shamsi-calendar/blob/main/shamsi-calendar%40gnome.scr.ir/prefs.js) را بررسی . بهتر هست از این ترفند استفاده شود تا همزمان هردو نسخه را پشتیبانی کند. بفرمایید

**Comment by omid** [comment]
ممنون.
هیچ پروژه‌ی نرم‌افزاری‌ای تا بینهایت پشتیبانی از کتابخونه‌های لگاسی رو نخواهد داشت.
پشتیبانی کردن از همه انواع مختلف، پیچیدگی پروژه و به روز رسانی رو دشوارتر خواهد کرد و در این ابعاد (نسخه گنوم) ترجیح می‌دم پشتیبانی دراپ بشه.
ضمن اینکه من امکان تست کامل روی همه نسخه‌های گنوم رو ندارم و به همین خاطر پشتیبانی رو دراپ می‌کنم.
کسی که برای پایداری از ال.تی.اس استفاده می‌کنه، و قدیمی‌تر بودن برنامه‌ها رو به جون خریده، به نظرم بهتره این رو هم قبول کنه که ممکنه آخرین نسخه‌های برنامه‌ها با همه‌ی محیط‌ها سازگار نباشند.
