### ISSUE TITLE
سازگاری با گنوم ۴۰

### ISSUE THREAD

**Issue by zzgraph** [omid/Persian-Calendar-for-Gnome-Shell#78]
در حال حاضر فدورا ورژن گنوم را به ۴۰ ارتقا داده و مانجارو هم در حالی که تمام اپلیکیشن‌های گنوم را به ۴۰ ارتقا داده، قرار است تا مدتی دیگر گنوم شل را هم به ۴۰ ارتقا دهد.
آیا امکان ارتقا سازگاری با گنوم چهل وجود دارد؟

**Comment by omid** [comment]
سلام، بله
من خودم از گنوم ۴۰٫۲ استفاده می‌کنم و مشکلی ندارم.

**Comment by omid** [comment]
تناقض رفتاری‌ای بین وب‌سایت گنوم‌شل و خود گنوم‌شل وجود داشت که باعث گمراه شدن من شده بود. الان باید درست باشه و بتونید از وب‌سایت هم بگیرید.
