### ISSUE TITLE
قبلا برای من کار میکرد ولی الان دوباره نصب کردم این خطا رو داره

### ISSUE THREAD

**Issue by MostafaRostami72** [omid/Persian-Calendar-for-Gnome-Shell#81]
![photo_2021-08-21_10-42-11](https://user-images.githubusercontent.com/62288229/130312511-9194e2f2-98a0-4fa6-99b0-f775c382bae1.jpg)

**Comment by omid** [comment]
<div dir="rtl">ورژن گنوم‌شل و اینکه چطوری نصب کردید رو هم بگید لطفن</div>

**Comment by MostafaRostami72** [comment]
GNOME Shell 3.36.9

همون مراحلی که توی readme هست نصب کردم 
clone
run make
بعد داخل tweaks میخوام برم داخل تنظیماتش این ارور میومد

**Comment by omid** [comment]
<div dir="rtl">
توی آخرین نسخه، گنوم نسخه ۳.۳۶ پشتیبانی نمی‌شه.
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/blob/master/PersianCalendar%40oxygenws.com/metadata.json

توصیه می‌کنم افزونه رو پاک کنید و از سایت گنوم نصب کنید:
https://extensions.gnome.org/extension/240/persian-calendar/
</div>

**Comment by MostafaRostami72** [comment]
با خود گنوم نصب کردم اوکی شد ممنون
