### ISSUE TITLE
عدم نصب

### ISSUE THREAD

**Issue by yourhonor1996** [omid/Persian-Calendar-for-Gnome-Shell#82]
سلام. 
من کارهایی رو که توی توضیحات گفته بودید رو انجام دادم ولی با این ارور مواجه شدم:
```
jq: error: Could not open file PersianCalendar@oxygenws.com/metadata.json: Permission denied
jq: error: Could not open file PersianCalendar@oxygenws.com/metadata.json: Permission denied
rm -fR ./_build
mkdir -p _build
cp -r PersianCalendar@oxygenws.com/* _build
# mkdir -p _build/locale
# cp -r PersianCalendar@oxygenws.com/locale/* _build/locale/
mkdir -p _build/schemas
cp PersianCalendar@oxygenws.com/schemas/*.xml _build/schemas/
cp PersianCalendar@oxygenws.com/schemas/gschemas.compiled _build/schemas/
sed -i 's/"version": /"version": 1/' _build/metadata.json;
rm -rf /root/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com
mkdir -p /root/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com
cp -r ./_build/* /root/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/
rm -fR _build
echo done
done

```

ورژن لینوکس من این هست:
20.04.3 LTS (Focal Fossa)

**Comment by omid** [comment]
<div dir="rtl">
در مجموع برای نصب نباید نیازی به jq باشه و این خودش یک باگه!

اما مشکل تو الان این نیست. می‌شه توی همون شاخه‌ای که make رو اجرا می‌کنی، خروجی `ls -l` رو اینجا بذاری؟
</div>

**Comment by omid** [comment]
<div dir="rtl">
این رو هم یادم رفت بگم، در هر صورت نسخه گیت احتمالن با نسخه گنوم شما سازگار نیست.
بهتره از خود سایت گنوم نصب کنید
</div>

**Comment by omid** [comment]
<div dir=rtl>
نیاز به jq رو برای نصب از بین بردم. الان نباید خطا ببینید.

اما به هر حال مورد بالا هنوز پابرجاست
</div>

**Comment by omid** [comment]
خوب چرا از سایت گنوم نصب نمی‌کنید؟

https://extensions.gnome.org/extension/240/

**Comment by yourhonor1996** [comment]
برای نصب کردن باید فایل های دانلود شده از اکستنشن رو داخل محل نصب کپی و پیست میکردم. منظورم این بود. برای پیدا کردن محل نصب اکستنشن هم باید توی اینترنت سرچ میکردم.

**Comment by omid** [comment]
خوب به نظر میاد که مشکل شما برطرف شده.
اگر همچنان مشکلی وجود داره، لطفن تیکت رو مجدد باز کنید یا یک تیکت جدید بزنید.
