### ISSUE TITLE
Can't go to settings

### ISSUE THREAD

**Issue by Aminmalek** [omid/Persian-Calendar-for-Gnome-Shell#83]
TypeError: this.main_hbox.append is not a function

Stack trace:
  PersianCalendarApp@/home/amin/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/prefs.js:46:24
  buildPrefsWidget@/home/amin/.local/share/gnome-shell/extensions/PersianCalendar@oxygenws.com/prefs.js:194:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by omid** [comment]
Please uninstall the extension and use the https://extensions.gnome.org website to install it.
