### ISSUE TITLE
وجود خطا در هنگام نصب در لینوکس مینت

### ISSUE THREAD

**Issue by sahelefard** [omid/Persian-Calendar-for-Gnome-Shell#87]
![image](https://user-images.githubusercontent.com/79420437/147510596-3f88e2e1-477c-4094-84e2-1d808b57075b.png)

**Comment by sahelefard** [comment]
آیا باید ریپازیتوری رو اینیت کنم؟فایل

**Comment by omid** [comment]
اکستنشن رو از سایت زیر دانلود کنید:

https://extensions.gnome.org/extension/240/persian-calendar/

**Comment by omid** [comment]
لطفن اگر مشکلی داشتید تیکت رو مجدد باز کنید.
