### ISSUE TITLE
امکان نمایش متنی ماه قمری و میلادی

### ISSUE THREAD

**Issue by rastikerdar** [omid/Persian-Calendar-for-Gnome-Shell#9]
سلام و تشکر برای این اپلت بسیار خوب!

منظورم مثلا ماه شعبان یا رجب یا ...
حالا برای میلادی میشه از اپلت اصلی گنوم استفاده کرد.

**Comment by omid** [comment]
سلام،

مدت‌ها بود چنین قابلیتی تو ذهنم بود... توی فایل «تودو!» هم نوشته بودم.
اما وقتی دیدم شما به عنوان یک فعال جامعه بازمتن اینو از من خواستید، نتونستم دیگه پشت گوش بندازم.

به نظرم چیزی که الان گذاشتم بیشتر از درخواست شما باشه، اما قطعن راضی کننده است :smile: 

موفق باشید

**Comment by rastikerdar** [comment]
دست شما درد نکند آقای متقی. عالی شد.

البته یک مشکل کوچولو دیدم شاید فقط به سیستم من مربوط بشه اینکه ماه فروردین رو اون پایین ۰۰ نشون میده و ماه اردیبهشت رو ۰۱  تا اسفند رو ۱۱.
![screenshot from 2016-04-15 08-39-37](https://cloud.githubusercontent.com/assets/3116038/14551259/efb56b1a-02e5-11e6-9b9a-5b8c37120f8e.png)

متشکرم

**Comment by omid** [comment]
درست می‌گی، ممنون. :-)

مرتفع شد.
