### ISSUE TITLE
مشکل نصب در کالی

### ISSUE THREAD

**Issue by mohammadmohammadiarchangel** [omid/Persian-Calendar-for-Gnome-Shell#94]
من طبق موارد گفته شده عمل کردم ولی این اکستنشن توی بخش تنظیمات اکستنشن ها برام اضافه نشده که بخواهم فعالش کنم؟

**Comment by omid** [comment]
لطفن بفرمایید که نسخه گنوم چنده و اینکه چطوری اکستنشن رو نصب کردید؟

**Comment by mohammadmohammadiarchangel** [comment]
گنوم ورژن 41.2

**Comment by mohammadmohammadiarchangel** [comment]
به وسیله ی گیت کلون کردم . بعد فایل میک-فایل رو کلیک راست کردم به صورت برنامه اجرا کردم.

**Comment by omid** [comment]
لطفن برنامه رو حذف کنید و از سایت گنوم نصب کنید:
https://extensions.gnome.org/extension/240/

**Comment by mohammadmohammadiarchangel** [comment]
ممنونم. مشکل از طریق راهی که گفتید حل شد.
