### ISSUE TITLE
Add support for gnome 42

### ISSUE THREAD

**Issue by mhkarimi1383** [omid/Persian-Calendar-for-Gnome-Shell#95]
please add support for gnome 42 since lots of users are using this version, because of features that it has

**Comment by omid** [comment]
We do support gnome 42.
I've just updated the way to install the extension in the README.md, please remove the extension and install it again.

**Comment by mhkarimi1383** [comment]
in extensions.gnome.org only gnome 41 is supported I will use other installation ways

**Comment by mhkarimi1383** [comment]
according to `metadata.json` file 
```json
  "shell-version": [
    "40",
    "41"
  ],
```
gnome 42 is not supported

**Comment by omid** [comment]
Oh yes, you are right, I don't know why I thought you mean Gnome Shell 41.2.
But Gnome Shell 42 is not yet released, is it?
What distro are you using?

**Comment by mhkarimi1383** [comment]
I'm using ArchLinux with testing repos enabled 🤓

**Comment by omid** [comment]
@mhkarimi1383 thanks. you can easily add 42 to the versions, test all functionalities and if it's fine, create a PR 👍🏼

**Comment by mhkarimi1383** [comment]
I have created a PR 
You can give gnome 42 a try ;)
