### ISSUE TITLE
رنگ نامشخص در تم های روشن

### ISSUE THREAD

**Issue by matin1099** [omid/Persian-Calendar-for-Gnome-Shell#98]
سلام امید 
اول تشکر کنم بابت تقویم باحالت.کل بچه های شرکت ازش راضی هستند.
اما یک نکته آزار دهنده وجود داره که نوشته های سایر تقویم ها(منظورم میلادی و قمری هست) روی تم های روشن(whitesur و adwaita و orchis رو که داریم استفاده میکنیم مطمن هستم) به شدت ناخوانا هست. 
خواستیم خودمون تغییر بدی که به شرط امانت به اون دست نزدیم و در عوض منتظر میشیم که آپشن امکان تغییر رنگ اون هم بهش اضافه شه!
با ارزوی بهترینا و سالی پر از موفقیت.
![Screenshot from 2022-03-29 23-49-01](https://user-images.githubusercontent.com/43605221/160690759-ca8b5246-54ca-425f-9a78-840cb3a42a09.png)
این تصویر white sur هست و نسخه 
تقویم درحال استفاده 92 هست روی gnome 40.5

**Comment by omid** [comment]
سلام،
خوشحالم که مفید بوده و ازش استفاده می‌کنید.
والا من از گنوم ۴۱ استفاده می‌کنم و نمی‌تونم نوار بالا رو سفید کنم!
حتا تمی که گفتی رو نصب کردم و نشد.
گویا توی گنوم ۴۲ هم نمی‌شه: https://i.imgur.com/xuoFMeo.gif
پیشنهاد من اینه که همرنگ اعداد روزها بشه. که توی گنوم تیره هم همینطوره.
تا جایی که یادم میاد کد این بخش تغییری نکرده و توی کد هم چیزی ندیدم که بخواد مشکل ایجاد کنه و css این بخش مشابه اعداد روزها است!

**Comment by eshagh79** [comment]
سلام، فکر کنم مشکل تم که نصب کردید باشه.
منم در اوبونتو ۲۱.۱۰ الان امتحان کردم و تاریخ‌های دیگر که بین جدول روزها و مبدل تاریخ هست رو بسیار کمرنگ نمایش میداد.
فکر کنم میتونید خودتون با اضافه کردن یه رنگ(مثلا: ) به کلاس «pcalendar-date-label» در پرونده stylesheet.css اونو اصلاح کنید.
`.pcalendar-date-label {
    padding: .4em 0;
    color: #333;
}`

**Comment by matin1099** [comment]
> سلام، خوشحالم که مفید بوده و ازش استفاده می‌کنید. والا من از گنوم ۴۱ استفاده می‌کنم و نمی‌تونم نوار بالا رو سفید کنم! حتا تمی که گفتی رو نصب کردم و نشد. گویا توی گنوم ۴۲ هم نمی‌شه: ![42](https://camo.githubusercontent.com/31b649985dc8886f1cf9e188903284dbc1749e7cc8c26e8a658215889766407f/68747470733a2f2f692e696d6775722e636f6d2f78756f464d656f2e676966) پیشنهاد من اینه که همرنگ اعداد روزها بشه. که توی گنوم تیره هم همینطوره. تا جایی که یادم میاد کد این بخش تغییری نکرده و توی کد هم چیزی ندیدم که بخواد مشکل ایجاد کنه و css این بخش مشابه اعداد روزها است!


بچه هامون برای وایت سور چون مک دوستاشتن داک و شل رو هم عوض کردن. ولی مشکل دو اون دوتا تم دیگه هم بود برای همین من شک کردم به ناسازگاری کد.
فعلا دستی تغییرش بدیم کارمون راه بیوفتنه تا آپدیتش بیاد :smiley: 
تغییر رنگش تو آپدیت میاد دیگه انشالله!!!!

**Comment by matin1099** [comment]
> سلام، فکر کنم مشکل تم که نصب کردید باشه. منم در اوبونتو ۲۱.۱۰ الان امتحان کردم و تاریخ‌های دیگر که بین جدول روزها و مبدل تاریخ هست رو بسیار کمرنگ نمایش میداد. فکر کنم میتونید خودتون با اضافه کردن یه رنگ(مثلا: ‎#333 ) به کلاس «pcalendar-date-label» در پرونده stylesheet.css اونو اصلاح کنید. `.pcalendar-date-label { padding: .4em 0; color: #333; }` با اینحال اگه روزی بخواین دوباره از تم تیره استفاده کنید، بازم مجبورید که این پرونده رو اصلاح کنید.

ممنونم از راهنماییتون

**Comment by omid** [comment]
> بچه هامون برای وایت سور چون مک دوستاشتن داک و شل رو هم عوض کردن. ولی مشکل دو اون دوتا تم دیگه هم بود برای همین من شک کردم به ناسازگاری کد.

به نظر میاد منظورم واضح نبود.
نوار بالا به هیچ عنوان برای من سفید نمی‌شه. حالا تم هر چی می‌خواد باشه. چه whitesur چه adwaita.
از چه دسترویی استفاده می‌کنید که بتونم دقیقن شرایط کاری شما رو شبیه‌سازی کنم؟

**Comment by omid** [comment]
این مورد برطرف شد.
البته تا موارد چندزبانگی برطرف نشه، نمی‌تونم نسخه جدید منتشر کنم. (شدن که می‌شه، اما فکر کنم مشکلات اون سریع حل بشه و بشه تا نهایت یکی دو هفته آینده منتشر کرد!)
